/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`get_next_settlement`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetNextSettlementError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_open_settlement`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetOpenSettlementError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_settlement`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSettlementError {
    Status404(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_settlement_captures`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSettlementCapturesError {
    Status400(models::ErrorResponse),
    Status404(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_settlement_chargebacks`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSettlementChargebacksError {
    Status400(models::ErrorResponse),
    Status404(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_settlement_payments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSettlementPaymentsError {
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_settlement_refunds`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSettlementRefundsError {
    Status400(models::ErrorResponse),
    Status404(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_settlements`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSettlementsError {
    Status400(models::ErrorResponse),
    Status404(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// Retrieve the details of the current settlement, that has not yet been paid out.  For a complete reference of the settlement object, refer to the [Get settlement endpoint](get-settlement) documentation.  For more accurate bookkeeping, refer to the [balance report](get-balance-report) endpoint or the [balance transactions](list-balance-transactions) endpoint.
pub async fn get_next_settlement(
    configuration: &configuration::Configuration,
    idempotency_key: Option<&str>,
) -> Result<models::EntitySettlement, Error<GetNextSettlementError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_idempotency_key = idempotency_key;

    let uri_str = format!("{}/v2/settlements/next", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_idempotency_key {
        req_builder = req_builder.header("idempotency-key", param_value.to_string());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EntitySettlement`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EntitySettlement`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetNextSettlementError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve the details of the open balance of the organization. This will return a settlement object representing your organization's balance.  For a complete reference of the settlement object, refer to the [Get settlement endpoint](get-settlement) documentation.  For more accurate bookkeeping, refer to the [balance report](get-balance-report) endpoint or the [balance transactions](list-balance-transactions) endpoint.
pub async fn get_open_settlement(
    configuration: &configuration::Configuration,
    idempotency_key: Option<&str>,
) -> Result<models::EntitySettlement, Error<GetOpenSettlementError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_idempotency_key = idempotency_key;

    let uri_str = format!("{}/v2/settlements/open", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_idempotency_key {
        req_builder = req_builder.header("idempotency-key", param_value.to_string());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EntitySettlement`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EntitySettlement`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetOpenSettlementError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve a single settlement by its ID.  To lookup settlements by their bank reference, replace the ID in the URL by a reference. For example: `1234567.2404.03`.  A settlement represents a transfer of your balance funds to your external bank account.  Settlements will typically include a report that details what balance transactions have taken place between this settlement and the previous one.  For more accurate bookkeeping, refer to the [balance report](get-balance-report) endpoint or the [balance transactions](list-balance-transactions) endpoint.
pub async fn get_settlement(
    configuration: &configuration::Configuration,
    settlement_id: &str,
    idempotency_key: Option<&str>,
) -> Result<models::EntitySettlement, Error<GetSettlementError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_settlement_id = settlement_id;
    let p_header_idempotency_key = idempotency_key;

    let uri_str = format!(
        "{}/v2/settlements/{settlementId}",
        configuration.base_path,
        settlementId = crate::apis::urlencode(p_path_settlement_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_idempotency_key {
        req_builder = req_builder.header("idempotency-key", param_value.to_string());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EntitySettlement`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EntitySettlement`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSettlementError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve all captures included in the given settlement.  The response is in the same format as the response of the [List captures endpoint](list-captures).
pub async fn list_settlement_captures(
    configuration: &configuration::Configuration,
    settlement_id: &str,
    from: Option<&str>,
    limit: Option<i32>,
    embed: Option<&str>,
    idempotency_key: Option<&str>,
) -> Result<models::ListSettlementCaptures200Response, Error<ListSettlementCapturesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_settlement_id = settlement_id;
    let p_query_from = from;
    let p_query_limit = limit;
    let p_query_embed = embed;
    let p_header_idempotency_key = idempotency_key;

    let uri_str = format!(
        "{}/v2/settlements/{settlementId}/captures",
        configuration.base_path,
        settlementId = crate::apis::urlencode(p_path_settlement_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_embed {
        req_builder = req_builder.query(&[("embed", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_idempotency_key {
        req_builder = req_builder.header("idempotency-key", param_value.to_string());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListSettlementCaptures200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListSettlementCaptures200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListSettlementCapturesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve all chargebacks 'deducted' from the given settlement.  The response is in the same format as the response of the [List chargebacks endpoint](list-chargebacks).
pub async fn list_settlement_chargebacks(
    configuration: &configuration::Configuration,
    settlement_id: &str,
    from: Option<&str>,
    limit: Option<i32>,
    embed: Option<&str>,
    testmode: Option<bool>,
    idempotency_key: Option<&str>,
) -> Result<models::ListSettlementChargebacks200Response, Error<ListSettlementChargebacksError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_settlement_id = settlement_id;
    let p_query_from = from;
    let p_query_limit = limit;
    let p_query_embed = embed;
    let p_query_testmode = testmode;
    let p_header_idempotency_key = idempotency_key;

    let uri_str = format!(
        "{}/v2/settlements/{settlementId}/chargebacks",
        configuration.base_path,
        settlementId = crate::apis::urlencode(p_path_settlement_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_embed {
        req_builder = req_builder.query(&[("embed", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_testmode {
        req_builder = req_builder.query(&[("testmode", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_idempotency_key {
        req_builder = req_builder.header("idempotency-key", param_value.to_string());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListSettlementChargebacks200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListSettlementChargebacks200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListSettlementChargebacksError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve all payments included in the given settlement.  The response is in the same format as the response of the [List payments endpoint](list-payments).  For capture-based payment methods such as Klarna, the payments are not listed here. Refer to the [List captures endpoint](list-captures) endpoint instead.
pub async fn list_settlement_payments(
    configuration: &configuration::Configuration,
    settlement_id: &str,
    from: Option<&str>,
    limit: Option<i32>,
    sort: Option<models::Sorting>,
    profile_id: Option<&str>,
    idempotency_key: Option<&str>,
) -> Result<models::ListSettlementPayments200Response, Error<ListSettlementPaymentsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_settlement_id = settlement_id;
    let p_query_from = from;
    let p_query_limit = limit;
    let p_query_sort = sort;
    let p_query_profile_id = profile_id;
    let p_header_idempotency_key = idempotency_key;

    let uri_str = format!(
        "{}/v2/settlements/{settlementId}/payments",
        configuration.base_path,
        settlementId = crate::apis::urlencode(p_path_settlement_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort {
        req_builder = req_builder.query(&[("sort", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_profile_id {
        req_builder = req_builder.query(&[("profileId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_idempotency_key {
        req_builder = req_builder.header("idempotency-key", param_value.to_string());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListSettlementPayments200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListSettlementPayments200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListSettlementPaymentsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve all refunds 'deducted' from the given settlement.  The response is in the same format as the response of the [List refunds endpoint](list-refunds).
pub async fn list_settlement_refunds(
    configuration: &configuration::Configuration,
    settlement_id: &str,
    from: Option<&str>,
    limit: Option<i32>,
    embed: Option<&str>,
    idempotency_key: Option<&str>,
) -> Result<models::ListSettlementRefunds200Response, Error<ListSettlementRefundsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_settlement_id = settlement_id;
    let p_query_from = from;
    let p_query_limit = limit;
    let p_query_embed = embed;
    let p_header_idempotency_key = idempotency_key;

    let uri_str = format!(
        "{}/v2/settlements/{settlementId}/refunds",
        configuration.base_path,
        settlementId = crate::apis::urlencode(p_path_settlement_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_embed {
        req_builder = req_builder.query(&[("embed", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_idempotency_key {
        req_builder = req_builder.header("idempotency-key", param_value.to_string());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListSettlementRefunds200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListSettlementRefunds200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListSettlementRefundsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve a list of all your settlements.  The results are paginated.
pub async fn list_settlements(
    configuration: &configuration::Configuration,
    from: Option<&str>,
    limit: Option<i32>,
    balance_id: Option<&str>,
    year: Option<&str>,
    month: Option<&str>,
    currencies: Option<models::Currencies>,
    idempotency_key: Option<&str>,
) -> Result<models::ListSettlements200Response, Error<ListSettlementsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_from = from;
    let p_query_limit = limit;
    let p_query_balance_id = balance_id;
    let p_query_year = year;
    let p_query_month = month;
    let p_query_currencies = currencies;
    let p_header_idempotency_key = idempotency_key;

    let uri_str = format!("{}/v2/settlements", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_balance_id {
        req_builder = req_builder.query(&[("balanceId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_year {
        req_builder = req_builder.query(&[("year", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_month {
        req_builder = req_builder.query(&[("month", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_currencies {
        req_builder = req_builder.query(&[("currencies", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_idempotency_key {
        req_builder = req_builder.header("idempotency-key", param_value.to_string());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListSettlements200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListSettlements200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListSettlementsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
