/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BalanceTransferDestinationType : The default destination of automatic scheduled transfers. Currently only `bank-account` is supported.  * `bank-account` — Transfer the balance amount to an external bank account
/// The default destination of automatic scheduled transfers. Currently only `bank-account` is supported.  * `bank-account` — Transfer the balance amount to an external bank account
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BalanceTransferDestinationType {
    #[serde(rename = "bank-account")]
    BankAccount,

}

impl std::fmt::Display for BalanceTransferDestinationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::BankAccount => write!(f, "bank-account"),
        }
    }
}

impl Default for BalanceTransferDestinationType {
    fn default() -> BalanceTransferDestinationType {
        Self::BankAccount
    }
}

