/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BalanceReportGrouping {
    #[serde(rename = "status-balances")]
    StatusBalances,
    #[serde(rename = "transaction-categories")]
    TransactionCategories,

}

impl std::fmt::Display for BalanceReportGrouping {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::StatusBalances => write!(f, "status-balances"),
            Self::TransactionCategories => write!(f, "transaction-categories"),
        }
    }
}

impl Default for BalanceReportGrouping {
    fn default() -> BalanceReportGrouping {
        Self::StatusBalances
    }
}

