/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BalanceCardIssuer {
    #[serde(rename = "amex")]
    Amex,
    #[serde(rename = "maestro")]
    Maestro,
    #[serde(rename = "carte-bancaire")]
    CarteBancaire,
    #[serde(rename = "other")]
    Other,

}

impl std::fmt::Display for BalanceCardIssuer {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Amex => write!(f, "amex"),
            Self::Maestro => write!(f, "maestro"),
            Self::CarteBancaire => write!(f, "carte-bancaire"),
            Self::Other => write!(f, "other"),
        }
    }
}

impl Default for BalanceCardIssuer {
    fn default() -> BalanceCardIssuer {
        Self::Amex
    }
}

