/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BalancePrepaymentPartType {
    #[serde(rename = "fee")]
    Fee,
    #[serde(rename = "fee-reimbursement")]
    FeeReimbursement,
    #[serde(rename = "fee-discount")]
    FeeDiscount,
    #[serde(rename = "fee-vat")]
    FeeVat,
    #[serde(rename = "fee-rounding-compensation")]
    FeeRoundingCompensation,

}

impl std::fmt::Display for BalancePrepaymentPartType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Fee => write!(f, "fee"),
            Self::FeeReimbursement => write!(f, "fee-reimbursement"),
            Self::FeeDiscount => write!(f, "fee-discount"),
            Self::FeeVat => write!(f, "fee-vat"),
            Self::FeeRoundingCompensation => write!(f, "fee-rounding-compensation"),
        }
    }
}

impl Default for BalancePrepaymentPartType {
    fn default() -> BalancePrepaymentPartType {
        Self::Fee
    }
}

