/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Balance : The balance of the business account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Balance {
    /// The total available balance of the business account.
    #[serde(rename = "total")]
    pub total: models::Amount,
}

impl Balance {
    /// The balance of the business account.
    pub fn new(total: models::Amount) -> Balance {
        Balance {
            total,
        }
    }
}

