/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BalanceTransactionType {
    #[serde(rename = "application-fee")]
    ApplicationFee,
    #[serde(rename = "capture")]
    Capture,
    #[serde(rename = "chargeback")]
    Chargeback,
    #[serde(rename = "chargeback-reversal")]
    ChargebackReversal,
    #[serde(rename = "failed-payment-fee")]
    FailedPaymentFee,
    #[serde(rename = "failed-payment")]
    FailedPayment,
    #[serde(rename = "invoice-compensation")]
    InvoiceCompensation,
    #[serde(rename = "payment")]
    Payment,
    #[serde(rename = "payment-fee")]
    PaymentFee,
    #[serde(rename = "payment-commission")]
    PaymentCommission,
    #[serde(rename = "refund")]
    Refund,
    #[serde(rename = "returned-refund")]
    ReturnedRefund,
    #[serde(rename = "returned-transfer")]
    ReturnedTransfer,
    #[serde(rename = "split-payment")]
    SplitPayment,
    #[serde(rename = "outgoing-transfer")]
    OutgoingTransfer,
    #[serde(rename = "capture-commission")]
    CaptureCommission,
    #[serde(rename = "canceled-outgoing-transfer")]
    CanceledOutgoingTransfer,
    #[serde(rename = "incoming-transfer")]
    IncomingTransfer,
    #[serde(rename = "api-payment-rolling-reserve-release")]
    ApiPaymentRollingReserveRelease,
    #[serde(rename = "capture-rolling-reserve-release")]
    CaptureRollingReserveRelease,
    #[serde(rename = "reimbursement-fee")]
    ReimbursementFee,
    #[serde(rename = "balance-correction")]
    BalanceCorrection,
    #[serde(rename = "unauthorized-direct-debit")]
    UnauthorizedDirectDebit,
    #[serde(rename = "bank-charged-failure-fee")]
    BankChargedFailureFee,
    #[serde(rename = "platform-payment-refund")]
    PlatformPaymentRefund,
    #[serde(rename = "refund-compensation")]
    RefundCompensation,
    #[serde(rename = "returned-refund-compensation")]
    ReturnedRefundCompensation,
    #[serde(rename = "returned-platform-payment-refund")]
    ReturnedPlatformPaymentRefund,
    #[serde(rename = "platform-payment-chargeback")]
    PlatformPaymentChargeback,
    #[serde(rename = "chargeback-compensation")]
    ChargebackCompensation,
    #[serde(rename = "reversed-platform-payment-chargeback")]
    ReversedPlatformPaymentChargeback,
    #[serde(rename = "reversed-chargeback-compensation")]
    ReversedChargebackCompensation,
    #[serde(rename = "failed-split-payment-platform")]
    FailedSplitPaymentPlatform,
    #[serde(rename = "failed-split-payment-compensation")]
    FailedSplitPaymentCompensation,
    #[serde(rename = "cash-advance-loan")]
    CashAdvanceLoan,
    #[serde(rename = "platform-connected-organizations-fee")]
    PlatformConnectedOrganizationsFee,
    #[serde(rename = "split-transaction")]
    SplitTransaction,
    #[serde(rename = "managed-fee")]
    ManagedFee,
    #[serde(rename = "returned-managed-fee")]
    ReturnedManagedFee,
    #[serde(rename = "topup")]
    Topup,
    #[serde(rename = "balance-reserve")]
    BalanceReserve,
    #[serde(rename = "balance-reserve-return")]
    BalanceReserveReturn,
    #[serde(rename = "movement")]
    Movement,
    #[serde(rename = "post-payment-split-payment")]
    PostPaymentSplitPayment,
    #[serde(rename = "cash-collateral-issuance")]
    CashCollateralIssuance,
    #[serde(rename = "cash-collateral-release")]
    CashCollateralRelease,

}

impl std::fmt::Display for BalanceTransactionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ApplicationFee => write!(f, "application-fee"),
            Self::Capture => write!(f, "capture"),
            Self::Chargeback => write!(f, "chargeback"),
            Self::ChargebackReversal => write!(f, "chargeback-reversal"),
            Self::FailedPaymentFee => write!(f, "failed-payment-fee"),
            Self::FailedPayment => write!(f, "failed-payment"),
            Self::InvoiceCompensation => write!(f, "invoice-compensation"),
            Self::Payment => write!(f, "payment"),
            Self::PaymentFee => write!(f, "payment-fee"),
            Self::PaymentCommission => write!(f, "payment-commission"),
            Self::Refund => write!(f, "refund"),
            Self::ReturnedRefund => write!(f, "returned-refund"),
            Self::ReturnedTransfer => write!(f, "returned-transfer"),
            Self::SplitPayment => write!(f, "split-payment"),
            Self::OutgoingTransfer => write!(f, "outgoing-transfer"),
            Self::CaptureCommission => write!(f, "capture-commission"),
            Self::CanceledOutgoingTransfer => write!(f, "canceled-outgoing-transfer"),
            Self::IncomingTransfer => write!(f, "incoming-transfer"),
            Self::ApiPaymentRollingReserveRelease => write!(f, "api-payment-rolling-reserve-release"),
            Self::CaptureRollingReserveRelease => write!(f, "capture-rolling-reserve-release"),
            Self::ReimbursementFee => write!(f, "reimbursement-fee"),
            Self::BalanceCorrection => write!(f, "balance-correction"),
            Self::UnauthorizedDirectDebit => write!(f, "unauthorized-direct-debit"),
            Self::BankChargedFailureFee => write!(f, "bank-charged-failure-fee"),
            Self::PlatformPaymentRefund => write!(f, "platform-payment-refund"),
            Self::RefundCompensation => write!(f, "refund-compensation"),
            Self::ReturnedRefundCompensation => write!(f, "returned-refund-compensation"),
            Self::ReturnedPlatformPaymentRefund => write!(f, "returned-platform-payment-refund"),
            Self::PlatformPaymentChargeback => write!(f, "platform-payment-chargeback"),
            Self::ChargebackCompensation => write!(f, "chargeback-compensation"),
            Self::ReversedPlatformPaymentChargeback => write!(f, "reversed-platform-payment-chargeback"),
            Self::ReversedChargebackCompensation => write!(f, "reversed-chargeback-compensation"),
            Self::FailedSplitPaymentPlatform => write!(f, "failed-split-payment-platform"),
            Self::FailedSplitPaymentCompensation => write!(f, "failed-split-payment-compensation"),
            Self::CashAdvanceLoan => write!(f, "cash-advance-loan"),
            Self::PlatformConnectedOrganizationsFee => write!(f, "platform-connected-organizations-fee"),
            Self::SplitTransaction => write!(f, "split-transaction"),
            Self::ManagedFee => write!(f, "managed-fee"),
            Self::ReturnedManagedFee => write!(f, "returned-managed-fee"),
            Self::Topup => write!(f, "topup"),
            Self::BalanceReserve => write!(f, "balance-reserve"),
            Self::BalanceReserveReturn => write!(f, "balance-reserve-return"),
            Self::Movement => write!(f, "movement"),
            Self::PostPaymentSplitPayment => write!(f, "post-payment-split-payment"),
            Self::CashCollateralIssuance => write!(f, "cash-collateral-issuance"),
            Self::CashCollateralRelease => write!(f, "cash-collateral-release"),
        }
    }
}

impl Default for BalanceTransactionType {
    fn default() -> BalanceTransactionType {
        Self::ApplicationFee
    }
}

