/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateWebhookRequestEventTypes {
    /// The list of events to enable for this webhook. You may specify `'*'` to add all events, except those that require explicit selection.
    ArrayVecWebhookEventTypes(Vec<models::WebhookEventTypes>),
    WebhookEventTypes(models::WebhookEventTypes),
}

impl Default for CreateWebhookRequestEventTypes {
    fn default() -> Self {
        Self::ArrayVecWebhookEventTypes(Default::default())
    }
}
