/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWebhookRequest {
    /// A name that identifies the webhook.
    #[serde(rename = "name")]
    pub name: String,
    /// The URL Mollie will send the events to. This URL must be publicly accessible.
    #[serde(rename = "url")]
    pub url: String,
    /// The list of events to enable for this webhook. You may specify `'*'` to add all events, except those that require explicit selection. Separate multiple event types with a comma.
    #[serde(rename = "eventTypes")]
    pub event_types: models::WebhookEventTypes,
    /// Whether to create the entity in test mode or live mode.  Most API credentials are specifically created for either live mode or test mode, in which case this parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
    #[serde(rename = "testmode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub testmode: Option<Option<bool>>,
}

impl CreateWebhookRequest {
    pub fn new(name: String, url: String, event_types: models::WebhookEventTypes) -> CreateWebhookRequest {
        CreateWebhookRequest {
            name,
            url,
            event_types,
            testmode: None,
        }
    }
}

