/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreditDebitIndicator : Indicates whether the entry is a credit or debit from the perspective of the account holder.
/// Indicates whether the entry is a credit or debit from the perspective of the account holder.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CreditDebitIndicator {
    #[serde(rename = "credit")]
    Credit,
    #[serde(rename = "debit")]
    Debit,

}

impl std::fmt::Display for CreditDebitIndicator {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Credit => write!(f, "credit"),
            Self::Debit => write!(f, "debit"),
        }
    }
}

impl Default for CreditDebitIndicator {
    fn default() -> CreditDebitIndicator {
        Self::Credit
    }
}

