/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Currencies {
    #[serde(rename = "EUR")]
    Eur,
    #[serde(rename = "GBP")]
    Gbp,
    #[serde(rename = "CHF")]
    Chf,
    #[serde(rename = "DKK")]
    Dkk,
    #[serde(rename = "NOK")]
    Nok,
    #[serde(rename = "PLN")]
    Pln,
    #[serde(rename = "SEK")]
    Sek,
    #[serde(rename = "USD")]
    Usd,
    #[serde(rename = "CZK")]
    Czk,
    #[serde(rename = "HUF")]
    Huf,
    #[serde(rename = "AUD")]
    Aud,
    #[serde(rename = "CAD")]
    Cad,

}

impl std::fmt::Display for Currencies {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Eur => write!(f, "EUR"),
            Self::Gbp => write!(f, "GBP"),
            Self::Chf => write!(f, "CHF"),
            Self::Dkk => write!(f, "DKK"),
            Self::Nok => write!(f, "NOK"),
            Self::Pln => write!(f, "PLN"),
            Self::Sek => write!(f, "SEK"),
            Self::Usd => write!(f, "USD"),
            Self::Czk => write!(f, "CZK"),
            Self::Huf => write!(f, "HUF"),
            Self::Aud => write!(f, "AUD"),
            Self::Cad => write!(f, "CAD"),
        }
    }
}

impl Default for Currencies {
    fn default() -> Currencies {
        Self::Eur
    }
}

