/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnableMethodIssuerRequest {
    /// When enabling a voucher issuer, an inbetween party may be involved which you have a contract with. Provide the contract ID for the first time you enable an issuer via this contractor.  You can update the contract ID as long as it is not approved yet, by repeating the API call with a different contract ID.
    #[serde(rename = "contractId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contract_id: Option<Option<String>>,
}

impl EnableMethodIssuerRequest {
    pub fn new() -> EnableMethodIssuerRequest {
        EnableMethodIssuerRequest {
            contract_id: None,
        }
    }
}

