/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityUnmatchedCreditTransferLinksSelf : The URL to this unmatched credit transfer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityUnmatchedCreditTransferLinksSelf {
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl EntityUnmatchedCreditTransferLinksSelf {
    /// The URL to this unmatched credit transfer.
    pub fn new() -> EntityUnmatchedCreditTransferLinksSelf {
        EntityUnmatchedCreditTransferLinksSelf {
            href: None,
            r#type: None,
        }
    }
}

