/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityBalanceReportTotals : Totals are grouped according to the chosen grouping rule. The example response should give a good idea of what a typical grouping looks like.  If grouping `status-balances` is chosen, the main grouping is as follows:  * `pendingBalance` containing an `open`, `pending`, `movedToAvailable`, and `close` sub-group * `availableBalance` containing an `open`, `movedFromPending`, `immediatelyAvailable`, and `close` sub-group  If grouping `transaction-categories` is chosen, the main grouping is as follows:  * `open` and `close` groups, each containing a `pending` and `available` sub-group * Transaction type groups such as `payments`, `refunds`, `chargebacks`, `capital`, `transfers`, `fee-prepayments`, `corrections`, `topups` each containing a `pending`, `movedToAvailable`, and `immediatelyAvailable` sub-group  Each sub-group typically has:  * An `amount` object containing the group's total amount * A `count` integer if relevant (for example, counting the number of refunds) * A `subtotals` array containing more sub-group objects if applicable
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityBalanceReportTotals {
    #[serde(rename = "pendingBalance", skip_serializing_if = "Option::is_none")]
    pub pending_balance: Option<models::EntityBalanceReportTotalsPendingBalance>,
    #[serde(rename = "availableBalance", skip_serializing_if = "Option::is_none")]
    pub available_balance: Option<models::EntityBalanceReportTotalsAvailableBalance>,
    #[serde(rename = "open", skip_serializing_if = "Option::is_none")]
    pub open: Option<models::EntityBalanceReportTotalsOpen>,
    #[serde(rename = "close", skip_serializing_if = "Option::is_none")]
    pub close: Option<models::EntityBalanceReportTotalsOpen>,
    #[serde(rename = "payments", skip_serializing_if = "Option::is_none")]
    pub payments: Option<models::EntityBalanceReportTotalsPayments>,
    #[serde(rename = "refunds", skip_serializing_if = "Option::is_none")]
    pub refunds: Option<models::EntityBalanceReportTotalsPayments>,
    #[serde(rename = "chargebacks", skip_serializing_if = "Option::is_none")]
    pub chargebacks: Option<models::EntityBalanceReportTotalsPayments>,
    #[serde(rename = "capital", skip_serializing_if = "Option::is_none")]
    pub capital: Option<models::EntityBalanceReportTotalsPayments>,
    #[serde(rename = "transfers", skip_serializing_if = "Option::is_none")]
    pub transfers: Option<models::EntityBalanceReportTotalsPayments>,
    #[serde(rename = "fee-prepayments", skip_serializing_if = "Option::is_none")]
    pub fee_prepayments: Option<models::EntityBalanceReportTotalsPayments>,
    #[serde(rename = "corrections", skip_serializing_if = "Option::is_none")]
    pub corrections: Option<models::EntityBalanceReportTotalsPayments>,
    #[serde(rename = "topups", skip_serializing_if = "Option::is_none")]
    pub topups: Option<models::EntityBalanceReportTotalsPayments>,
}

impl EntityBalanceReportTotals {
    /// Totals are grouped according to the chosen grouping rule. The example response should give a good idea of what a typical grouping looks like.  If grouping `status-balances` is chosen, the main grouping is as follows:  * `pendingBalance` containing an `open`, `pending`, `movedToAvailable`, and `close` sub-group * `availableBalance` containing an `open`, `movedFromPending`, `immediatelyAvailable`, and `close` sub-group  If grouping `transaction-categories` is chosen, the main grouping is as follows:  * `open` and `close` groups, each containing a `pending` and `available` sub-group * Transaction type groups such as `payments`, `refunds`, `chargebacks`, `capital`, `transfers`, `fee-prepayments`, `corrections`, `topups` each containing a `pending`, `movedToAvailable`, and `immediatelyAvailable` sub-group  Each sub-group typically has:  * An `amount` object containing the group's total amount * A `count` integer if relevant (for example, counting the number of refunds) * A `subtotals` array containing more sub-group objects if applicable
    pub fn new() -> EntityBalanceReportTotals {
        EntityBalanceReportTotals {
            pending_balance: None,
            available_balance: None,
            open: None,
            close: None,
            payments: None,
            refunds: None,
            chargebacks: None,
            capital: None,
            transfers: None,
            fee_prepayments: None,
            corrections: None,
            topups: None,
        }
    }
}

