/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityBusinessAccount {
    /// Indicates the response contains a business account object. Will always contain the string `business-account` for this endpoint.
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    /// The identifier uniquely referring to this business account. Mollie assigns this identifier at account creation time.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "accountDetails", skip_serializing_if = "Option::is_none")]
    pub account_details: Option<models::AccountDetails>,
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<models::Balance>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::AccountStatus>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::Mode>,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl EntityBusinessAccount {
    pub fn new() -> EntityBusinessAccount {
        EntityBusinessAccount {
            resource: None,
            id: None,
            account_details: None,
            balance: None,
            status: None,
            mode: None,
            created_at: None,
        }
    }
}

