/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityMandateLinks : An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityMandateLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::Url>,
    /// The API resource URL of the [customer](get-customer) that this mandate belongs to.
    #[serde(rename = "customer")]
    pub customer: Box<models::Url>,
    #[serde(rename = "documentation")]
    pub documentation: Box<models::Url>,
}

impl EntityMandateLinks {
    /// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
    pub fn new(param_self: models::Url, customer: models::Url, documentation: models::Url) -> EntityMandateLinks {
        EntityMandateLinks {
            param_self: Box::new(param_self),
            customer: Box::new(customer),
            documentation: Box::new(documentation),
        }
    }
}

