/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityBalanceReportTotalsAvailableBalance : The available balance. Only available if grouping is `status-balances`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityBalanceReportTotalsAvailableBalance {
    #[serde(rename = "open", skip_serializing_if = "Option::is_none")]
    pub open: Option<models::SubGroup>,
    #[serde(rename = "movedFromPending", skip_serializing_if = "Option::is_none")]
    pub moved_from_pending: Option<models::SubGroup>,
    #[serde(rename = "immediatelyAvailable", skip_serializing_if = "Option::is_none")]
    pub immediately_available: Option<models::SubGroup>,
    #[serde(rename = "close", skip_serializing_if = "Option::is_none")]
    pub close: Option<models::SubGroup>,
}

impl EntityBalanceReportTotalsAvailableBalance {
    /// The available balance. Only available if grouping is `status-balances`.
    pub fn new() -> EntityBalanceReportTotalsAvailableBalance {
        EntityBalanceReportTotalsAvailableBalance {
            open: None,
            moved_from_pending: None,
            immediately_available: None,
            close: None,
        }
    }
}

