/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityMethodAllAllOfPricing {
    /// A description of what the pricing applies to. For example, a specific country (`The Netherlands`) or a category of cards (`American Express`). If a `locale` is provided, the description may be translated.
    #[serde(rename = "description")]
    pub description: String,
    /// The fixed price charged per payment.
    #[serde(rename = "fixed")]
    pub fixed: models::Amount,
    /// The variable price charged per payment, as a percentage string.
    #[serde(rename = "variable")]
    pub variable: String,
    /// Only present for credit card pricing. It will correspond with the `feeRegion` of credit card payments as returned in the [Payments API](get-payment).
    #[serde(rename = "feeRegion", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fee_region: Option<Option<String>>,
}

impl EntityMethodAllAllOfPricing {
    pub fn new(description: String, fixed: models::Amount, variable: String) -> EntityMethodAllAllOfPricing {
        EntityMethodAllAllOfPricing {
            description,
            fixed,
            variable,
            fee_region: None,
        }
    }
}

