/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityUnmatchedCreditTransferLinks : Links to related resources.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityUnmatchedCreditTransferLinks {
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<models::EntityUnmatchedCreditTransferLinksSelf>,
    #[serde(rename = "documentation", skip_serializing_if = "Option::is_none")]
    pub documentation: Option<models::EntityUnmatchedCreditTransferLinksDocumentation>,
}

impl EntityUnmatchedCreditTransferLinks {
    /// Links to related resources.
    pub fn new() -> EntityUnmatchedCreditTransferLinks {
        EntityUnmatchedCreditTransferLinks {
            param_self: None,
            documentation: None,
        }
    }
}

