/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityProfile {
    /// Indicates the response contains a profile object. Will always contain the string `profile` for this endpoint.
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    /// The identifier uniquely referring to this profile. Example: `pfl_v9hTwCvYqw`.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::Mode>,
    /// The profile's name, this will usually reflect the trade name or brand name of the profile's website or application.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The URL to the profile's website or application. Only `https` or `http` URLs are allowed. No `@` signs are allowed.
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    /// The email address associated with the profile's trade name or brand.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The phone number associated with the profile's trade name or brand.
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    /// The products or services offered by the profile's website or application.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A list of countries where you expect that the majority of the profile's customers reside, in [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) format.
    #[serde(rename = "countriesOfActivity", skip_serializing_if = "Option::is_none")]
    pub countries_of_activity: Option<Vec<String>>,
    /// The industry associated with the profile's trade name or brand. Please refer to the [business category list](common-data-types#business-category) for all possible options.
    #[serde(rename = "businessCategory", skip_serializing_if = "Option::is_none")]
    pub business_category: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ProfileStatus>,
    #[serde(rename = "review", skip_serializing_if = "Option::is_none")]
    pub review: Option<Box<models::EntityProfileReview>>,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::EntityProfileLinks>>,
}

impl EntityProfile {
    pub fn new() -> EntityProfile {
        EntityProfile {
            resource: None,
            id: None,
            mode: None,
            name: None,
            website: None,
            email: None,
            phone: None,
            description: None,
            countries_of_activity: None,
            business_category: None,
            status: None,
            review: None,
            created_at: None,
            _links: None,
        }
    }
}

