/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityWebhookEventLinks : An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityWebhookEventLinks {
    #[serde(rename = "self")]
    pub param_self: models::Url,
    #[serde(rename = "documentation")]
    pub documentation: models::Url,
    /// The API resource URL of the entity that this event belongs to.
    #[serde(rename = "entity", skip_serializing_if = "Option::is_none")]
    pub entity: Option<models::Url>,
}

impl EntityWebhookEventLinks {
    /// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
    pub fn new(param_self: models::Url, documentation: models::Url) -> EntityWebhookEventLinks {
        EntityWebhookEventLinks {
            param_self,
            documentation,
            entity: None,
        }
    }
}

