/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityUnmatchedCreditTransferAction {
    /// The resource type of the object.
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    /// The identifier uniquely referring to this unmatched credit transfer action.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The identifier of the unmatched credit transfer this action belongs to.
    #[serde(rename = "unmatchedCreditTransferId", skip_serializing_if = "Option::is_none")]
    pub unmatched_credit_transfer_id: Option<String>,
    /// The action performed on the unmatched credit transfer.
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<models::UnmatchedCreditTransferActionType>,
    /// The current status of the action.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::UnmatchedCreditTransferActionStatus>,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<models::EntityUnmatchedCreditTransferActionDetails>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<models::EntityUnmatchedCreditTransferActionLinks>,
}

impl EntityUnmatchedCreditTransferAction {
    pub fn new() -> EntityUnmatchedCreditTransferAction {
        EntityUnmatchedCreditTransferAction {
            resource: None,
            id: None,
            unmatched_credit_transfer_id: None,
            action: None,
            status: None,
            created_at: None,
            details: None,
            _links: None,
        }
    }
}

