/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityUnmatchedCreditTransferRemittanceInformationReferences : Structured references provided with the unmatched credit transfer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityUnmatchedCreditTransferRemittanceInformationReferences {
    /// The creditor reference.
    #[serde(rename = "creditorReference", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub creditor_reference: Option<Option<String>>,
    /// The end-to-end identifier.
    #[serde(rename = "endToEndId", skip_serializing_if = "Option::is_none")]
    pub end_to_end_id: Option<String>,
}

impl EntityUnmatchedCreditTransferRemittanceInformationReferences {
    /// Structured references provided with the unmatched credit transfer.
    pub fn new() -> EntityUnmatchedCreditTransferRemittanceInformationReferences {
        EntityUnmatchedCreditTransferRemittanceInformationReferences {
            creditor_reference: None,
            end_to_end_id: None,
        }
    }
}

