/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityBalanceTransactionContextReturnedTransfer {
    #[serde(rename = "transferId", skip_serializing_if = "Option::is_none")]
    pub transfer_id: Option<String>,
    #[serde(rename = "settlementId", skip_serializing_if = "Option::is_none")]
    pub settlement_id: Option<String>,
}

impl EntityBalanceTransactionContextReturnedTransfer {
    pub fn new() -> EntityBalanceTransactionContextReturnedTransfer {
        EntityBalanceTransactionContextReturnedTransfer {
            transfer_id: None,
            settlement_id: None,
        }
    }
}

