/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityBalanceTransferStatusReason : The reason for the current status of the transfer, if applicable.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityBalanceTransferStatusReason {
    #[serde(rename = "code")]
    pub code: models::BalanceTransferStatusReason,
    /// A description of the status reason, localized according to the transfer.
    #[serde(rename = "message")]
    pub message: String,
}

impl EntityBalanceTransferStatusReason {
    /// The reason for the current status of the transfer, if applicable.
    pub fn new(code: models::BalanceTransferStatusReason, message: String) -> EntityBalanceTransferStatusReason {
        EntityBalanceTransferStatusReason {
            code,
            message,
        }
    }
}

