/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityClientLinkResponse {
    /// Indicates the response contains a client link object. Will always contain the string `client-link` for this endpoint.
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    /// The identifier uniquely referring to this client link. Example: `cl_vZCnNQsV2UtfXxYifWKWH`.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<models::EntityClientLinkOwner>,
    /// Name of the organization.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<models::EntityClientLinkAddress>,
    /// The registration number of the organization at their local chamber of commerce.
    #[serde(rename = "registrationNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub registration_number: Option<Option<String>>,
    /// The VAT number of the organization, if based in the European Union. VAT numbers are verified against the international registry *VIES*.
    #[serde(rename = "vatNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vat_number: Option<Option<String>>,
    /// The legal entity type of the organization, based on its country of origin. Please refer to the [legal entity list](common-data-types#legal-entity) for all possible options.
    #[serde(rename = "legalEntity", skip_serializing_if = "Option::is_none")]
    pub legal_entity: Option<String>,
    /// The registration office that the organization was registered at. Please refer to the [registration office list](common-data-types#registration-office) for all possible options.
    #[serde(rename = "registrationOffice", skip_serializing_if = "Option::is_none")]
    pub registration_office: Option<String>,
    /// The incorporation date of the organization (format `YYYY-MM-DD`)
    #[serde(rename = "incorporationDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub incorporation_date: Option<Option<String>>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<models::EntityClientLinkLinks>,
}

impl EntityClientLinkResponse {
    pub fn new() -> EntityClientLinkResponse {
        EntityClientLinkResponse {
            resource: None,
            id: None,
            owner: None,
            name: None,
            address: None,
            registration_number: None,
            vat_number: None,
            legal_entity: None,
            registration_office: None,
            incorporation_date: None,
            _links: None,
        }
    }
}

