/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityBalanceTransactionContextSplitPayment {
    #[serde(rename = "paymentId", skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<String>,
    #[serde(rename = "paymentDescription", skip_serializing_if = "Option::is_none")]
    pub payment_description: Option<String>,
    #[serde(rename = "paymentOnwer", skip_serializing_if = "Option::is_none")]
    pub payment_onwer: Option<String>,
}

impl EntityBalanceTransactionContextSplitPayment {
    pub fn new() -> EntityBalanceTransactionContextSplitPayment {
        EntityBalanceTransactionContextSplitPayment {
            payment_id: None,
            payment_description: None,
            payment_onwer: None,
        }
    }
}

