/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityChargeback {
    /// Indicates the response contains a chargeback object. Will always contain the string `chargeback` for this endpoint.
    #[serde(rename = "resource")]
    pub resource: String,
    #[serde(rename = "id")]
    pub id: String,
    /// The amount charged back by the customer.
    #[serde(rename = "amount")]
    pub amount: models::Amount,
    /// This optional field will contain the approximate amount that will be deducted from your account balance, converted to the currency your account is settled in.  The amount is a **negative** amount.  Since the field contains an estimated amount during chargeback processing, it may change over time. To retrieve accurate settlement amounts we recommend using the [List balance transactions endpoint](list-balance-transactions) instead.
    #[serde(rename = "settlementAmount", skip_serializing_if = "Option::is_none")]
    pub settlement_amount: Option<models::AmountNullable>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<models::EntityChargebackReason>,
    #[serde(rename = "paymentId")]
    pub payment_id: String,
    #[serde(rename = "settlementId", skip_serializing_if = "Option::is_none")]
    pub settlement_id: Option<String>,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The date and time the chargeback was reversed if applicable, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "reversedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reversed_at: Option<Option<String>>,
    #[serde(rename = "_links")]
    pub _links: models::EntityRefundLinks,
}

impl EntityChargeback {
    pub fn new(resource: String, id: String, amount: models::Amount, payment_id: String, created_at: String, _links: models::EntityRefundLinks) -> EntityChargeback {
        EntityChargeback {
            resource,
            id,
            amount,
            settlement_amount: None,
            reason: None,
            payment_id,
            settlement_id: None,
            created_at,
            reversed_at: None,
            _links,
        }
    }
}

