/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityClientLinkLinks : An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityClientLinkLinks {
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<models::Url>,
    /// The link you can send your customer to, where they can either log in and link their account, or sign up and proceed with onboarding.
    #[serde(rename = "clientLink", skip_serializing_if = "Option::is_none")]
    pub client_link: Option<models::Url>,
    #[serde(rename = "documentation", skip_serializing_if = "Option::is_none")]
    pub documentation: Option<models::Url>,
}

impl EntityClientLinkLinks {
    /// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
    pub fn new() -> EntityClientLinkLinks {
        EntityClientLinkLinks {
            param_self: None,
            client_link: None,
            documentation: None,
        }
    }
}

