/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntitySessionPayment {
    /// The webhook URL where we will send payment status updates to.  This URL will be automatically set as the webhook URL for all payments created for this session.
    #[serde(rename = "webhookUrl", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<String>,
}

impl EntitySessionPayment {
    pub fn new() -> EntitySessionPayment {
        EntitySessionPayment {
            webhook_url: None,
        }
    }
}

