/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntitySettlementPeriodsValueValueCostsInner {
    /// A description of the cost subtotal
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "method", deserialize_with = "Option::deserialize")]
    pub method: Option<models::PaymentMethod>,
    /// The number of fees
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "rate")]
    pub rate: Box<models::EntitySettlementPeriodsValueValueCostsInnerRate>,
    /// The net total cost, i.e. excluding VAT
    #[serde(rename = "amountNet")]
    pub amount_net: Box<models::Amount>,
    /// The applicable VAT
    #[serde(rename = "amountVat")]
    pub amount_vat: Box<models::AmountNullable>,
    /// The gross total cost, i.e. including VAT
    #[serde(rename = "amountGross")]
    pub amount_gross: Box<models::Amount>,
}

impl EntitySettlementPeriodsValueValueCostsInner {
    pub fn new(description: String, method: Option<models::PaymentMethod>, count: i32, rate: models::EntitySettlementPeriodsValueValueCostsInnerRate, amount_net: models::Amount, amount_vat: models::AmountNullable, amount_gross: models::Amount) -> EntitySettlementPeriodsValueValueCostsInner {
        EntitySettlementPeriodsValueValueCostsInner {
            description,
            method,
            count,
            rate: Box::new(rate),
            amount_net: Box::new(amount_net),
            amount_vat: Box::new(amount_vat),
            amount_gross: Box::new(amount_gross),
        }
    }
}

