/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityClientLinks : An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityClientLinks {
    #[serde(rename = "self")]
    pub param_self: models::Url,
    /// The API resource URL of the client's organization.
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<models::Url>,
    /// The API resource URL of the client's onboarding status.
    #[serde(rename = "onboarding", skip_serializing_if = "Option::is_none")]
    pub onboarding: Option<models::Url>,
    #[serde(rename = "documentation", skip_serializing_if = "Option::is_none")]
    pub documentation: Option<models::Url>,
}

impl EntityClientLinks {
    /// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
    pub fn new(param_self: models::Url) -> EntityClientLinks {
        EntityClientLinks {
            param_self,
            organization: None,
            onboarding: None,
            documentation: None,
        }
    }
}

