/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityUnmatchedCreditTransferRemittanceInformation : Remittance information provided with the unmatched credit transfer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityUnmatchedCreditTransferRemittanceInformation {
    /// Unstructured remittance information, such as a free-text payment description.
    #[serde(rename = "unstructured", skip_serializing_if = "Option::is_none")]
    pub unstructured: Option<String>,
    #[serde(rename = "references", skip_serializing_if = "Option::is_none")]
    pub references: Option<models::EntityUnmatchedCreditTransferRemittanceInformationReferences>,
}

impl EntityUnmatchedCreditTransferRemittanceInformation {
    /// Remittance information provided with the unmatched credit transfer.
    pub fn new() -> EntityUnmatchedCreditTransferRemittanceInformation {
        EntityUnmatchedCreditTransferRemittanceInformation {
            unstructured: None,
            references: None,
        }
    }
}

