/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntitySalesInvoice {
    /// Indicates the response contains a sales invoice object. Will always contain the string `sales-invoice` for this endpoint.
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Whether to create the entity in test mode or live mode.  Most API credentials are specifically created for either live mode or test mode, in which case this parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
    #[serde(rename = "testmode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub testmode: Option<Option<bool>>,
    /// When issued, an invoice number will be set for the sales invoice.
    #[serde(rename = "invoiceNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invoice_number: Option<Option<String>>,
    /// The identifier referring to the [profile](get-profile) this entity belongs to.  Most API credentials are linked to a single profile. In these cases the `profileId` can be omitted in the creation request. For organization-level credentials such as OAuth access tokens however, the `profileId` parameter is required.
    #[serde(rename = "profileId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub profile_id: Option<Option<String>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::SalesInvoiceStatus>,
    #[serde(rename = "vatScheme", skip_serializing_if = "Option::is_none")]
    pub vat_scheme: Option<models::SalesInvoiceVatScheme>,
    #[serde(rename = "vatMode", skip_serializing_if = "Option::is_none")]
    pub vat_mode: Option<models::SalesInvoiceVatMode>,
    /// A free-form memo you can set on the invoice, and will be shown on the invoice PDF.
    #[serde(rename = "memo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub memo: Option<Option<String>>,
    /// Provide any data you like as a JSON object. We will save the data alongside the entity. Whenever you fetch the entity with our API, we will also include the metadata. You can use up to approximately 1kB.
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<serde_json::Value>>,
    #[serde(rename = "paymentTerm", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_term: Option<Option<models::SalesInvoicePaymentTerm>>,
    /// Used when setting an invoice to status of `paid`, and will store a payment that fully pays the invoice with the provided details. Required for `paid` status.
    #[serde(rename = "paymentDetails", skip_serializing_if = "Option::is_none")]
    pub payment_details: Option<Box<models::SalesInvoicePaymentDetails>>,
    /// Used when setting an invoice to status of either `issued` or `paid`. Will be used to issue the invoice to the recipient with the provided `subject` and `body`. Required for `issued` status.
    #[serde(rename = "emailDetails", skip_serializing_if = "Option::is_none")]
    pub email_details: Option<Box<models::SalesInvoiceEmailDetails>>,
    /// The identifier referring to the [customer](get-customer) you want to attempt an automated payment for. If provided, `mandateId` becomes required as well. Only allowed for invoices with status `paid`.
    #[serde(rename = "customerId", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
    /// The identifier referring to the [mandate](get-mandate) you want to use for the automated payment. If provided, `customerId` becomes required as well. Only allowed for invoices with status `paid`.
    #[serde(rename = "mandateId", skip_serializing_if = "Option::is_none")]
    pub mandate_id: Option<String>,
    /// An identifier tied to the recipient data. This should be a unique value based on data your system contains, so that both you and us know who we're referring to. It is a value you provide to us so that recipient management is not required to send a first invoice to a recipient.
    #[serde(rename = "recipientIdentifier", skip_serializing_if = "Option::is_none")]
    pub recipient_identifier: Option<String>,
    #[serde(rename = "recipient", skip_serializing_if = "Option::is_none")]
    pub recipient: Option<Box<models::SalesInvoiceRecipient>>,
    /// Provide the line items for the invoice. Each line contains details such as a description of the item ordered and its price.  All lines must have the same currency as the invoice.
    #[serde(rename = "lines", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lines: Option<Option<Vec<models::SalesInvoiceLineItem>>>,
    /// The discount to be applied to the entire invoice, applied on top of any line item discounts.
    #[serde(rename = "discount", skip_serializing_if = "Option::is_none")]
    pub discount: Option<Box<models::SalesInvoiceDiscount>>,
    /// The amount that is left to be paid.
    #[serde(rename = "amountDue", skip_serializing_if = "Option::is_none")]
    pub amount_due: Option<Box<models::Amount>>,
    /// The total amount without VAT before discounts.
    #[serde(rename = "subtotalAmount", skip_serializing_if = "Option::is_none")]
    pub subtotal_amount: Option<Box<models::Amount>>,
    /// The total amount with VAT.
    #[serde(rename = "totalAmount", skip_serializing_if = "Option::is_none")]
    pub total_amount: Option<Box<models::Amount>>,
    /// The total VAT amount.
    #[serde(rename = "totalVatAmount", skip_serializing_if = "Option::is_none")]
    pub total_vat_amount: Option<Box<models::Amount>>,
    /// The total amount without VAT after discounts.
    #[serde(rename = "discountedSubtotalAmount", skip_serializing_if = "Option::is_none")]
    pub discounted_subtotal_amount: Option<Box<models::Amount>>,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// If issued, the date when the sales invoice was issued, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "issuedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub issued_at: Option<Option<String>>,
    /// If paid, the date when the sales invoice was paid, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "paidAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<Option<String>>,
    /// If issued, the date when the sales invoice payment is due, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "dueAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub due_at: Option<Option<String>>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::EntitySalesInvoiceLinks>>,
}

impl EntitySalesInvoice {
    pub fn new() -> EntitySalesInvoice {
        EntitySalesInvoice {
            resource: None,
            id: None,
            testmode: None,
            invoice_number: None,
            profile_id: None,
            status: None,
            vat_scheme: None,
            vat_mode: None,
            memo: None,
            metadata: None,
            payment_term: None,
            payment_details: None,
            email_details: None,
            customer_id: None,
            mandate_id: None,
            recipient_identifier: None,
            recipient: None,
            lines: None,
            discount: None,
            amount_due: None,
            subtotal_amount: None,
            total_amount: None,
            total_vat_amount: None,
            discounted_subtotal_amount: None,
            created_at: None,
            issued_at: None,
            paid_at: None,
            due_at: None,
            _links: None,
        }
    }
}

