/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityPaymentLinks : An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityPaymentLinks {
    #[serde(rename = "self")]
    pub param_self: models::Url,
    /// The URL your customer should visit to make the payment. This is where you should redirect the customer to.
    #[serde(rename = "checkout", skip_serializing_if = "Option::is_none")]
    pub checkout: Option<models::Url>,
    /// The deeplink URL to the app of the payment method. Currently only available for `bancontact`.
    #[serde(rename = "mobileAppCheckout", skip_serializing_if = "Option::is_none")]
    pub mobile_app_checkout: Option<models::Url>,
    /// For test mode payments in certain scenarios, a hosted interface is available to help you test different payment states.  Firstly, for recurring test mode payments. Recurring payments do not have a checkout URL, because these payments are executed without any user interaction.  Secondly, for paid test mode payments. The payment state screen will then allow you to create a refund or chargeback for the test payment.
    #[serde(rename = "changePaymentState", skip_serializing_if = "Option::is_none")]
    pub change_payment_state: Option<models::Url>,
    /// Direct link to the payment in the Mollie Dashboard.
    #[serde(rename = "dashboard")]
    pub dashboard: models::Url,
    /// The API resource URL of the [refunds](list-payment-refunds) that belong to this payment.
    #[serde(rename = "refunds", skip_serializing_if = "Option::is_none")]
    pub refunds: Option<models::Url>,
    /// The API resource URL of the [chargebacks](list-payment-chargebacks) that belong to this payment.
    #[serde(rename = "chargebacks", skip_serializing_if = "Option::is_none")]
    pub chargebacks: Option<models::Url>,
    /// The API resource URL of the [captures](list-payment-captures) that belong to this payment.
    #[serde(rename = "captures", skip_serializing_if = "Option::is_none")]
    pub captures: Option<models::Url>,
    /// The API resource URL of the [settlement](get-settlement) this payment has been settled with. Not present if not yet settled.
    #[serde(rename = "settlement", skip_serializing_if = "Option::is_none")]
    pub settlement: Option<models::Url>,
    /// The API resource URL of the [customer](get-customer).
    #[serde(rename = "customer", skip_serializing_if = "Option::is_none")]
    pub customer: Option<models::Url>,
    /// The API resource URL of the [mandate](get-mandate).
    #[serde(rename = "mandate", skip_serializing_if = "Option::is_none")]
    pub mandate: Option<models::Url>,
    /// The API resource URL of the [subscription](get-subscription).
    #[serde(rename = "subscription", skip_serializing_if = "Option::is_none")]
    pub subscription: Option<models::Url>,
    /// The API resource URL of the [order](get-order) this payment was created for. Not present if not created for an order.
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<models::Url>,
    /// The API resource URL of the [terminal](get-terminal) this payment was created for. Only present for point-of-sale payments.
    #[serde(rename = "terminal", skip_serializing_if = "Option::is_none")]
    pub terminal: Option<models::Url>,
    #[serde(rename = "documentation", skip_serializing_if = "Option::is_none")]
    pub documentation: Option<models::Url>,
    /// Link to customer-facing page showing the status of the bank transfer (to verify if the transaction was successful).
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::Url>,
    /// Link to Mollie Checkout page allowing customers to select a different payment method instead of legacy bank transfer.
    #[serde(rename = "payOnline", skip_serializing_if = "Option::is_none")]
    pub pay_online: Option<models::Url>,
}

impl EntityPaymentLinks {
    /// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
    pub fn new(param_self: models::Url, dashboard: models::Url) -> EntityPaymentLinks {
        EntityPaymentLinks {
            param_self,
            checkout: None,
            mobile_app_checkout: None,
            change_payment_state: None,
            dashboard,
            refunds: None,
            chargebacks: None,
            captures: None,
            settlement: None,
            customer: None,
            mandate: None,
            subscription: None,
            order: None,
            terminal: None,
            documentation: None,
            status: None,
            pay_online: None,
        }
    }
}

