/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityRefund {
    /// Indicates the response contains a refund object. Will always contain the string `refund` for this endpoint.
    #[serde(rename = "resource")]
    pub resource: String,
    /// The identifier uniquely referring to this refund. Mollie assigns this identifier at refund creation time. Mollie will always refer to the refund by this ID. Example: `re_4qqhO89gsT`.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "mode")]
    pub mode: models::Mode,
    /// The description of the refund that may be shown to your customer, depending on the payment method used.
    #[serde(rename = "description")]
    pub description: String,
    /// The amount refunded to your customer with this refund. The amount is allowed to be lower than the original payment amount.
    #[serde(rename = "amount")]
    pub amount: models::Amount,
    /// **Deprecated.** This field will be removed on January 1st, 2027. Use the [Settlements API](list-settlements) or the [List balance transactions endpoint](list-balance-transactions) for settlement data.  The amount deducted from your account balance for this refund, converted to the currency your account is settled in. Always a **negative** amount. Only available once the refund is finalized and the final settlement amount has been determined.  For refunds not directly processed by Mollie (e.g. PayPal), the settlement amount is zero.
    #[serde(rename = "settlementAmount", skip_serializing_if = "Option::is_none")]
    pub settlement_amount: Option<models::AmountNullable>,
    #[serde(rename = "metadata", deserialize_with = "Option::deserialize")]
    pub metadata: Option<models::Metadata>,
    /// The unique identifier of the payment this refund was created for. The full payment object can be retrieved via the payment URL in the `_links` object.
    #[serde(rename = "paymentId", skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<String>,
    /// The identifier referring to the settlement this refund was settled with. This field is omitted if the refund is not settled (yet).
    #[serde(rename = "settlementId", skip_serializing_if = "Option::is_none")]
    pub settlement_id: Option<String>,
    #[serde(rename = "status")]
    pub status: models::RefundStatus,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "externalReference", skip_serializing_if = "Option::is_none")]
    pub external_reference: Option<models::EntityRefundExternalReference>,
    /// *This feature is only available to marketplace operators.*  With Mollie Connect you can charge fees on payments that your app is processing on behalf of other Mollie merchants, by providing the `routing` object during [payment creation](create-payment).  When creating refunds for these *routed* payments, by default the full amount is deducted from your balance.  If you want to pull back the funds that were routed to the connected merchant(s), you can set this parameter to `true` when issuing a full refund.  For more fine-grained control and for partial refunds, use the `routingReversals` parameter instead.
    #[serde(rename = "reverseRouting", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reverse_routing: Option<Option<bool>>,
    /// *This feature is only available to marketplace operators.*  When creating refunds for *routed* payments, by default the full amount is deducted from your balance.  If you want to pull back funds from the connected merchant(s), you can use this parameter to specify what amount needs to be reversed from which merchant(s).  If you simply want to fully reverse the routed funds, you can also use the `reverseRouting` parameter instead.
    #[serde(rename = "routingReversals", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub routing_reversals: Option<Option<Vec<models::EntityRefundRoutingReversalsInner>>>,
    /// Whether to create the entity in test mode or live mode.  Most API credentials are specifically created for either live mode or test mode, in which case this parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
    #[serde(rename = "testmode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub testmode: Option<Option<bool>>,
    #[serde(rename = "_links")]
    pub _links: models::EntityRefundLinks,
}

impl EntityRefund {
    pub fn new(resource: String, id: String, mode: models::Mode, description: String, amount: models::Amount, metadata: Option<models::Metadata>, status: models::RefundStatus, created_at: String, _links: models::EntityRefundLinks) -> EntityRefund {
        EntityRefund {
            resource,
            id,
            mode,
            description,
            amount,
            settlement_amount: None,
            metadata,
            payment_id: None,
            settlement_id: None,
            status,
            created_at,
            external_reference: None,
            reverse_routing: None,
            routing_reversals: None,
            testmode: None,
            _links,
        }
    }
}

