/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityBalanceReportTotalsOpen : Only available on `transaction-categories` grouping.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityBalanceReportTotalsOpen {
    #[serde(rename = "pending", skip_serializing_if = "Option::is_none")]
    pub pending: Option<Box<models::SubGroup>>,
    #[serde(rename = "available", skip_serializing_if = "Option::is_none")]
    pub available: Option<Box<models::SubGroup>>,
}

impl EntityBalanceReportTotalsOpen {
    /// Only available on `transaction-categories` grouping.
    pub fn new() -> EntityBalanceReportTotalsOpen {
        EntityBalanceReportTotalsOpen {
            pending: None,
            available: None,
        }
    }
}

