/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityBalanceTransactionContextInvoiceCompensation {
    #[serde(rename = "invoiceId", skip_serializing_if = "Option::is_none")]
    pub invoice_id: Option<String>,
}

impl EntityBalanceTransactionContextInvoiceCompensation {
    pub fn new() -> EntityBalanceTransactionContextInvoiceCompensation {
        EntityBalanceTransactionContextInvoiceCompensation {
            invoice_id: None,
        }
    }
}

