/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityCapabilityRequirementLinksDashboard : If known, a deep link to the Mollie dashboard of the client, where the requirement can be fulfilled. For example, where necessary documents are to be uploaded.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityCapabilityRequirementLinksDashboard {
    /// The actual URL string.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    /// The content type of the page or endpoint the URL points to.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl EntityCapabilityRequirementLinksDashboard {
    /// If known, a deep link to the Mollie dashboard of the client, where the requirement can be fulfilled. For example, where necessary documents are to be uploaded.
    pub fn new() -> EntityCapabilityRequirementLinksDashboard {
        EntityCapabilityRequirementLinksDashboard {
            href: None,
            r#type: None,
        }
    }
}

