/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityCapture {
    /// Indicates the response contains a capture object. Will always contain the string `capture` for this endpoint.
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::Mode>,
    /// The description of the capture.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The amount captured. If no amount is provided, the full authorized amount is captured.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Box<models::AmountNullable>>,
    /// This optional field will contain the approximate amount that will be settled to your account, converted to the currency your account is settled in.  Since the field contains an estimated amount during capture processing, it may change over time. To retrieve accurate settlement amounts we recommend using the [List balance transactions endpoint](list-balance-transactions) instead.
    #[serde(rename = "settlementAmount", skip_serializing_if = "Option::is_none")]
    pub settlement_amount: Option<Box<models::AmountNullable>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::CaptureStatus>,
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<Box<models::Metadata>>>,
    #[serde(rename = "paymentId", skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<String>,
    #[serde(rename = "shipmentId", skip_serializing_if = "Option::is_none")]
    pub shipment_id: Option<String>,
    #[serde(rename = "settlementId", skip_serializing_if = "Option::is_none")]
    pub settlement_id: Option<String>,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<Box<models::EntityCaptureLinks>>,
}

impl EntityCapture {
    pub fn new() -> EntityCapture {
        EntityCapture {
            resource: None,
            id: None,
            mode: None,
            description: None,
            amount: None,
            settlement_amount: None,
            status: None,
            metadata: None,
            payment_id: None,
            shipment_id: None,
            settlement_id: None,
            created_at: None,
            _links: None,
        }
    }
}

