/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityBalanceTransferPartyResponse : A party involved in the balance transfer, either the sender or the receiver.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityBalanceTransferPartyResponse {
    #[serde(rename = "type")]
    pub r#type: models::BalanceTransferPartyTypeResponse,
    /// Identifier of the party. For example, this contains the organization token if the type is `organization`.
    #[serde(rename = "id")]
    pub id: String,
    /// The transfer description for the transfer party. This is the description that will appear in the financial reports of the party.
    #[serde(rename = "description")]
    pub description: String,
}

impl EntityBalanceTransferPartyResponse {
    /// A party involved in the balance transfer, either the sender or the receiver.
    pub fn new(r#type: models::BalanceTransferPartyTypeResponse, id: String, description: String) -> EntityBalanceTransferPartyResponse {
        EntityBalanceTransferPartyResponse {
            r#type,
            id,
            description,
        }
    }
}

