/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityTerminal {
    /// Indicates the response contains a terminal object. Will always contain the string `terminal` for this endpoint.
    #[serde(rename = "resource")]
    pub resource: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "mode")]
    pub mode: models::Mode,
    /// A short description of the terminal. The description can be used as an identifier for the terminal. Currently, the description is set when the terminal is initially configured. It will be visible in the Mollie Dashboard, and it may be visible on the device itself depending on the device.
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "status")]
    pub status: models::TerminalStatus,
    #[serde(rename = "brand", deserialize_with = "Option::deserialize")]
    pub brand: Option<models::TerminalBrand>,
    #[serde(rename = "model", deserialize_with = "Option::deserialize")]
    pub model: Option<models::TerminalModel>,
    /// The serial number of the terminal. The serial number is provided at terminal creation time.
    #[serde(rename = "serialNumber", deserialize_with = "Option::deserialize")]
    pub serial_number: Option<String>,
    /// The currency configured on the terminal, in ISO 4217 format. Currently most of our terminals are bound to a specific currency, chosen during setup.
    #[serde(rename = "currency")]
    pub currency: String,
    /// The identifier referring to the [profile](get-profile) this entity belongs to.  Most API credentials are linked to a single profile. In these cases the `profileId` can be omitted in the creation request. For organization-level credentials such as OAuth access tokens however, the `profileId` parameter is required.
    #[serde(rename = "profileId")]
    pub profile_id: String,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "_links")]
    pub _links: models::EntityWebhookLinks,
}

impl EntityTerminal {
    pub fn new(resource: String, id: String, mode: models::Mode, description: String, status: models::TerminalStatus, brand: Option<models::TerminalBrand>, model: Option<models::TerminalModel>, serial_number: Option<String>, currency: String, profile_id: String, created_at: String, updated_at: String, _links: models::EntityWebhookLinks) -> EntityTerminal {
        EntityTerminal {
            resource,
            id,
            mode,
            description,
            status,
            brand,
            model,
            serial_number,
            currency,
            profile_id,
            created_at,
            updated_at,
            _links,
        }
    }
}

