/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityCapability {
    /// Always the word `capability` for this resource type.
    #[serde(rename = "resource")]
    pub resource: String,
    /// A unique name for this capability like `payments` / `settlements`.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: models::CapabilityStatus,
    #[serde(rename = "statusReason", deserialize_with = "Option::deserialize")]
    pub status_reason: Option<models::CapabilityStatusReason>,
    #[serde(rename = "requirements")]
    pub requirements: Vec<models::EntityCapabilityRequirement>,
}

impl EntityCapability {
    pub fn new(resource: String, name: String, status: models::CapabilityStatus, status_reason: Option<models::CapabilityStatusReason>, requirements: Vec<models::EntityCapabilityRequirement>) -> EntityCapability {
        EntityCapability {
            resource,
            name,
            status,
            status_reason,
            requirements,
        }
    }
}

