/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EntityWebhookEventEmbeddedEntity {
    PaymentLinkResponse(models::PaymentLinkResponse),
    EntityProfileResponse(models::EntityProfileResponse),
}

impl Default for EntityWebhookEventEmbeddedEntity {
    fn default() -> Self {
        Self::PaymentLinkResponse(Default::default())
    }
}

