/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityBalanceTransactionContextChargeback {
    #[serde(rename = "paymentId", skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<String>,
    #[serde(rename = "paymentDescription", skip_serializing_if = "Option::is_none")]
    pub payment_description: Option<String>,
    #[serde(rename = "chargebackId", skip_serializing_if = "Option::is_none")]
    pub chargeback_id: Option<String>,
    #[serde(rename = "chargebackDescription", skip_serializing_if = "Option::is_none")]
    pub chargeback_description: Option<String>,
}

impl EntityBalanceTransactionContextChargeback {
    pub fn new() -> EntityBalanceTransactionContextChargeback {
        EntityBalanceTransactionContextChargeback {
            payment_id: None,
            payment_description: None,
            chargeback_id: None,
            chargeback_description: None,
        }
    }
}

