/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityUnmatchedCreditTransferActionDetails : Additional details about the action.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityUnmatchedCreditTransferActionDetails {
    /// The IDs of the payments matched to the unmatched credit transfer.
    #[serde(rename = "paymentIds", skip_serializing_if = "Option::is_none")]
    pub payment_ids: Option<Vec<String>>,
}

impl EntityUnmatchedCreditTransferActionDetails {
    /// Additional details about the action.
    pub fn new() -> EntityUnmatchedCreditTransferActionDetails {
        EntityUnmatchedCreditTransferActionDetails {
            payment_ids: None,
        }
    }
}

