/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityUnmatchedCreditTransferActionLinksDocumentation : The URL to the documentation of this endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityUnmatchedCreditTransferActionLinksDocumentation {
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl EntityUnmatchedCreditTransferActionLinksDocumentation {
    /// The URL to the documentation of this endpoint.
    pub fn new() -> EntityUnmatchedCreditTransferActionLinksDocumentation {
        EntityUnmatchedCreditTransferActionLinksDocumentation {
            href: None,
            r#type: None,
        }
    }
}

