/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityBalanceReport {
    /// Indicates the response contains a balance report object. Will always contain the string `balance-report` for this endpoint.
    #[serde(rename = "resource")]
    pub resource: String,
    /// The ID of the balance this report is generated for.
    #[serde(rename = "balanceId")]
    pub balance_id: String,
    /// The time zone used for the from and until parameters. Currently only time zone `Europe/Amsterdam` is supported.
    #[serde(rename = "timeZone")]
    pub time_zone: String,
    /// The start date of the report, in `YYYY-MM-DD` format. The from date is 'inclusive', and in Central European Time. This means a report with for example `from=2024-01-01` will include movements of 2024-01-01 00:00:00 CET and onwards.
    #[serde(rename = "from")]
    pub from: String,
    /// The end date of the report, in `YYYY-MM-DD` format. The until date is 'exclusive', and in Central European Time. This means a report with for example `until=2024-02-01` will include movements up until 2024-01-31 23:59:59 CET.
    #[serde(rename = "until")]
    pub until: String,
    #[serde(rename = "grouping")]
    pub grouping: models::BalanceReportGrouping,
    #[serde(rename = "totals")]
    pub totals: models::EntityBalanceReportTotals,
    #[serde(rename = "_links")]
    pub _links: models::EntityBalanceLinks,
}

impl EntityBalanceReport {
    pub fn new(resource: String, balance_id: String, time_zone: String, from: String, until: String, grouping: models::BalanceReportGrouping, totals: models::EntityBalanceReportTotals, _links: models::EntityBalanceLinks) -> EntityBalanceReport {
        EntityBalanceReport {
            resource,
            balance_id,
            time_zone,
            from,
            until,
            grouping,
            totals,
            _links,
        }
    }
}

