/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityMethodImage : URLs of images representing the payment method.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityMethodImage {
    /// The URL pointing to an icon of 32 by 24 pixels.
    #[serde(rename = "size1x")]
    pub size1x: String,
    /// The URL pointing to an icon of 64 by 48 pixels.
    #[serde(rename = "size2x")]
    pub size2x: String,
    /// The URL pointing to a vector version of the icon. Usage of this format is preferred, since the icon can scale to any desired size without compromising visual quality.
    #[serde(rename = "svg")]
    pub svg: String,
}

impl EntityMethodImage {
    /// URLs of images representing the payment method.
    pub fn new(size1x: String, size2x: String, svg: String) -> EntityMethodImage {
        EntityMethodImage {
            size1x,
            size2x,
            svg,
        }
    }
}

