/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityPaymentRouteLinks : An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityPaymentRouteLinks {
    #[serde(rename = "self")]
    pub param_self: models::Url,
    /// The API resource URL of the [payment](get-payment) that belong to this route.
    #[serde(rename = "payment")]
    pub payment: models::Url,
}

impl EntityPaymentRouteLinks {
    /// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
    pub fn new(param_self: models::Url, payment: models::Url) -> EntityPaymentRouteLinks {
        EntityPaymentRouteLinks {
            param_self,
            payment,
        }
    }
}

