/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityRouteDestination : The destination of the route.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityRouteDestination {
    #[serde(rename = "type")]
    pub r#type: models::RouteDestinationTypeResponse,
    #[serde(rename = "organizationId")]
    pub organization_id: String,
}

impl EntityRouteDestination {
    /// The destination of the route.
    pub fn new(r#type: models::RouteDestinationTypeResponse, organization_id: String) -> EntityRouteDestination {
        EntityRouteDestination {
            r#type,
            organization_id,
        }
    }
}

