/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorResponse : An error response object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// The status code of the error message. This is always the same code as the status code of the HTTP message itself.
    #[serde(rename = "status")]
    pub status: i32,
    /// The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
    #[serde(rename = "title")]
    pub title: String,
    /// A detailed human-readable description of the error that occurred.
    #[serde(rename = "detail")]
    pub detail: String,
    /// If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    #[serde(rename = "_links")]
    pub _links: models::ErrorResponseLinks,
}

impl ErrorResponse {
    /// An error response object.
    pub fn new(status: i32, title: String, detail: String, _links: models::ErrorResponseLinks) -> ErrorResponse {
        ErrorResponse {
            status,
            title,
            detail,
            field: None,
            _links,
        }
    }
}

