/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExtraParameterParametersCompany : Billie is a business-to-business (B2B) payment method. It requires extra information to identify the organization that is completing the payment. It is recommended to include these parameters up front for a seamless flow. Otherwise, Billie will ask the customer to complete the missing fields during checkout.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtraParameterParametersCompany {
    /// The organization's registration number.
    #[serde(rename = "registrationNumber", skip_serializing_if = "Option::is_none")]
    pub registration_number: Option<String>,
    /// The organization's VAT number.
    #[serde(rename = "vatNumber", skip_serializing_if = "Option::is_none")]
    pub vat_number: Option<String>,
    /// The organization's entity type.
    #[serde(rename = "entityType", skip_serializing_if = "Option::is_none")]
    pub entity_type: Option<String>,
}

impl ExtraParameterParametersCompany {
    /// Billie is a business-to-business (B2B) payment method. It requires extra information to identify the organization that is completing the payment. It is recommended to include these parameters up front for a seamless flow. Otherwise, Billie will ask the customer to complete the missing fields during checkout.
    pub fn new() -> ExtraParameterParametersCompany {
        ExtraParameterParametersCompany {
            registration_number: None,
            vat_number: None,
            entity_type: None,
        }
    }
}

