/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPartnerStatus200ResponseUserAgentTokensInner {
    /// The unique User-Agent token.
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// The date from which the token is active, in ISO 8601 format.
    #[serde(rename = "startsAt", skip_serializing_if = "Option::is_none")]
    pub starts_at: Option<String>,
    /// The date until when the token will be active, in ISO 8601 format. Will be `null` if the token does not have an end date (yet).
    #[serde(rename = "endsAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ends_at: Option<Option<String>>,
}

impl GetPartnerStatus200ResponseUserAgentTokensInner {
    pub fn new() -> GetPartnerStatus200ResponseUserAgentTokensInner {
        GetPartnerStatus200ResponseUserAgentTokensInner {
            token: None,
            starts_at: None,
            ends_at: None,
        }
    }
}

