/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPartnerStatus200Response {
    /// Indicates the response contains a partner status object. Will always contain the string `partner` for this endpoint.
    #[serde(rename = "resource")]
    pub resource: String,
    /// Indicates the type of partner. Will be `null` if the currently authenticated organization is not enrolled as a partner.
    #[serde(rename = "partnerType", deserialize_with = "Option::deserialize")]
    pub partner_type: Option<PartnerType>,
    /// Whether the current organization is receiving commissions.
    #[serde(rename = "isCommissionPartner", skip_serializing_if = "Option::is_none")]
    pub is_commission_partner: Option<bool>,
    /// Array of User-Agent token objects. Present if the organization is a partner of type `useragent`, or if they were in the past.
    #[serde(rename = "userAgentTokens", skip_serializing_if = "Option::is_none")]
    pub user_agent_tokens: Option<Vec<models::GetPartnerStatus200ResponseUserAgentTokensInner>>,
    /// The date the partner contract was signed, in ISO 8601 format. Omitted if no contract has been signed (yet).
    #[serde(rename = "partnerContractSignedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub partner_contract_signed_at: Option<Option<String>>,
    /// Whether an update to the partner contract is available and requiring the organization's agreement.
    #[serde(rename = "partnerContractUpdateAvailable", skip_serializing_if = "Option::is_none")]
    pub partner_contract_update_available: Option<bool>,
    /// The expiration date of the signed partner contract, in ISO 8601 format. Omitted if contract has no expiration date (yet).
    #[serde(rename = "partnerContractExpiresAt", skip_serializing_if = "Option::is_none")]
    pub partner_contract_expires_at: Option<String>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<models::GetPartnerStatus200ResponseLinks>,
}

impl GetPartnerStatus200Response {
    pub fn new(resource: String, partner_type: Option<PartnerType>) -> GetPartnerStatus200Response {
        GetPartnerStatus200Response {
            resource,
            partner_type,
            is_commission_partner: None,
            user_agent_tokens: None,
            partner_contract_signed_at: None,
            partner_contract_update_available: None,
            partner_contract_expires_at: None,
            _links: None,
        }
    }
}
/// Indicates the type of partner. Will be `null` if the currently authenticated organization is not enrolled as a partner.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PartnerType {
    #[serde(rename = "oauth")]
    Oauth,
    #[serde(rename = "signuplink")]
    Signuplink,
    #[serde(rename = "useragent")]
    Useragent,
}

impl Default for PartnerType {
    fn default() -> PartnerType {
        Self::Oauth
    }
}

