/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Giftcard {
    /// Indicates the response contains a payment method issuer object. Will always contain the string `issuer` for this endpoint.
    #[serde(rename = "resource")]
    pub resource: String,
    /// The unique identifier of the payment method issuer.
    #[serde(rename = "id")]
    pub id: String,
    /// The full name of the payment method issuer.
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "status")]
    pub status: models::MethodIssuerStatus,
    #[serde(rename = "_links")]
    pub _links: models::EntityBalanceLinks,
}

impl Giftcard {
    pub fn new(resource: String, id: String, description: String, status: models::MethodIssuerStatus, _links: models::EntityBalanceLinks) -> Giftcard {
        Giftcard {
            resource,
            id,
            description,
            status,
            _links,
        }
    }
}

