/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListLinks : Links to help navigate through the lists of items. Every URL object will contain an `href` and a `type` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListLinks {
    /// The URL to the current set of items.
    #[serde(rename = "self")]
    pub param_self: Box<models::Url>,
    /// The previous set of items, if available.
    #[serde(rename = "previous")]
    pub previous: Box<models::UrlNullable>,
    /// The next set of items, if available.
    #[serde(rename = "next")]
    pub next: Box<models::UrlNullable>,
    #[serde(rename = "documentation")]
    pub documentation: Box<models::Url>,
}

impl ListLinks {
    /// Links to help navigate through the lists of items. Every URL object will contain an `href` and a `type` field.
    pub fn new(param_self: models::Url, previous: models::UrlNullable, next: models::UrlNullable, documentation: models::Url) -> ListLinks {
        ListLinks {
            param_self: Box::new(param_self),
            previous: Box::new(previous),
            next: Box::new(next),
            documentation: Box::new(documentation),
        }
    }
}

