/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListBusinessAccountTransactions200ResponseEmbedded {
    /// An array of transaction objects.
    #[serde(rename = "transactions", skip_serializing_if = "Option::is_none")]
    pub transactions: Option<Vec<models::TransactionResponse>>,
}

impl ListBusinessAccountTransactions200ResponseEmbedded {
    pub fn new() -> ListBusinessAccountTransactions200ResponseEmbedded {
        ListBusinessAccountTransactions200ResponseEmbedded {
            transactions: None,
        }
    }
}

