/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListEntityChargebackLinks : An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEntityChargebackLinks {
    #[serde(rename = "self")]
    pub param_self: models::Url,
    /// The API resource URL of the [payment](get-payment) that this chargeback belongs to.
    #[serde(rename = "payment")]
    pub payment: models::Url,
    /// The API resource URL of the [settlement](get-settlement) this chargeback has been settled with. Not present if not yet settled.
    #[serde(rename = "settlement", skip_serializing_if = "Option::is_none")]
    pub settlement: Option<models::UrlNullable>,
}

impl ListEntityChargebackLinks {
    /// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
    pub fn new(param_self: models::Url, payment: models::Url) -> ListEntityChargebackLinks {
        ListEntityChargebackLinks {
            param_self,
            payment,
            settlement: None,
        }
    }
}

