/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListCaptureResponse {
    /// Indicates the response contains a capture object. Will always contain the string `capture` for this endpoint.
    #[serde(rename = "resource")]
    pub resource: String,
    /// The identifier uniquely referring to this capture. Example: `cpt_mNepDkEtco6ah3QNPUGYH`.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "mode")]
    pub mode: models::Mode,
    /// The description of the capture.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The amount captured. If no amount is provided, the full authorized amount is captured.
    #[serde(rename = "amount")]
    pub amount: models::AmountNullable,
    /// **Deprecated.** This field will be removed on January 1st, 2027. Use the [Settlements API](list-settlements) or the [List balance transactions endpoint](list-balance-transactions) for settlement data.  The amount that will be settled to your account for this capture, converted to the currency your account is settled in. Only available once the capture is finalized and the final settlement amount has been determined.
    #[serde(rename = "settlementAmount", skip_serializing_if = "Option::is_none")]
    pub settlement_amount: Option<models::AmountNullable>,
    #[serde(rename = "status")]
    pub status: models::CaptureStatusResponse,
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<models::Metadata>>,
    /// The unique identifier of the payment this capture was created for. For example: `tr_5B8cwPMGnU6qLbRvo7qEZo`. The full payment object can be retrieved via the payment URL in the `_links` object.
    #[serde(rename = "paymentId")]
    pub payment_id: String,
    /// The unique identifier of the shipment that triggered the creation of this capture, if applicable. For example: `shp_gNapNy9qQTUFZYnCrCF7J`.
    #[serde(rename = "shipmentId", skip_serializing_if = "Option::is_none")]
    pub shipment_id: Option<String>,
    /// The identifier referring to the settlement this capture was settled with. For example, `stl_BkEjN2eBb`. This field is omitted if the capture is not settled (yet).
    #[serde(rename = "settlementId", skip_serializing_if = "Option::is_none")]
    pub settlement_id: Option<String>,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "_links")]
    pub _links: models::ListEntityCaptureLinks,
}

impl ListCaptureResponse {
    pub fn new(resource: String, id: String, mode: models::Mode, amount: models::AmountNullable, status: models::CaptureStatusResponse, payment_id: String, created_at: String, _links: models::ListEntityCaptureLinks) -> ListCaptureResponse {
        ListCaptureResponse {
            resource,
            id,
            mode,
            description: None,
            amount,
            settlement_amount: None,
            status,
            metadata: None,
            payment_id,
            shipment_id: None,
            settlement_id: None,
            created_at,
            _links,
        }
    }
}

