/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEntityWebhook {
    /// Indicates the response contains a webhook subscription object. Will always contain the string `webhook` for this endpoint.
    #[serde(rename = "resource")]
    pub resource: String,
    /// The identifier uniquely referring to this subscription.
    #[serde(rename = "id")]
    pub id: String,
    /// The subscription's events destination.
    #[serde(rename = "url")]
    pub url: String,
    /// The identifier uniquely referring to the profile that created the subscription.
    #[serde(rename = "profileId", deserialize_with = "Option::deserialize")]
    pub profile_id: Option<String>,
    /// The subscription's date time of creation.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The subscription's name.
    #[serde(rename = "name")]
    pub name: String,
    /// The events types that are subscribed.
    #[serde(rename = "eventTypes")]
    pub event_types: Vec<models::WebhookEventTypesResponse>,
    #[serde(rename = "status")]
    pub status: models::WebhookStatus,
    #[serde(rename = "mode")]
    pub mode: models::Mode,
    #[serde(rename = "_links")]
    pub _links: models::EntitySessionLinks,
}

impl ListEntityWebhook {
    pub fn new(resource: String, id: String, url: String, profile_id: Option<String>, created_at: String, name: String, event_types: Vec<models::WebhookEventTypesResponse>, status: models::WebhookStatus, mode: models::Mode, _links: models::EntitySessionLinks) -> ListEntityWebhook {
        ListEntityWebhook {
            resource,
            id,
            url,
            profile_id,
            created_at,
            name,
            event_types,
            status,
            mode,
            _links,
        }
    }
}

