/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListCustomerResponse {
    /// Indicates the response contains a customer object. Will always contain the string `customer` for this endpoint.
    #[serde(rename = "resource")]
    pub resource: String,
    /// The identifier uniquely referring to this customer. Example: `cst_vsKJpSsabw`.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "mode")]
    pub mode: models::Mode,
    /// The full name of the customer.
    #[serde(rename = "name")]
    pub name: String,
    /// The email address of the customer.  If the domain contains non-ASCII characters, encode it as Punycode per [RFC 3492](https://www.rfc-editor.org/rfc/rfc3492).
    #[serde(rename = "email")]
    pub email: String,
    /// Preconfigure the language to be used in the hosted payment pages shown to the customer. Should only be provided if absolutely necessary. If not provided, the browser language will be used which is typically highly accurate.
    #[serde(rename = "locale", deserialize_with = "Option::deserialize")]
    pub locale: Option<models::LocaleResponse>,
    #[serde(rename = "metadata", deserialize_with = "Option::deserialize")]
    pub metadata: Option<models::Metadata>,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// Whether to create the entity in test mode or live mode.  Most API credentials are specifically created for either live mode or test mode, in which case this parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
    #[serde(rename = "testmode", skip_serializing_if = "Option::is_none")]
    pub testmode: Option<bool>,
    #[serde(rename = "_links")]
    pub _links: models::ListEntityCustomerLinks,
}

impl ListCustomerResponse {
    pub fn new(resource: String, id: String, mode: models::Mode, name: String, email: String, locale: Option<models::LocaleResponse>, metadata: Option<models::Metadata>, created_at: String, _links: models::ListEntityCustomerLinks) -> ListCustomerResponse {
        ListCustomerResponse {
            resource,
            id,
            mode,
            name,
            email,
            locale,
            metadata,
            created_at,
            testmode: None,
            _links,
        }
    }
}

