/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListBalanceTransactions200ResponseEmbedded {
    /// An array of balance transaction objects.
    #[serde(rename = "balance_transactions")]
    pub balance_transactions: Vec<models::EntityBalanceTransaction>,
}

impl ListBalanceTransactions200ResponseEmbedded {
    pub fn new(balance_transactions: Vec<models::EntityBalanceTransaction>) -> ListBalanceTransactions200ResponseEmbedded {
        ListBalanceTransactions200ResponseEmbedded {
            balance_transactions,
        }
    }
}

