/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListInvoices200ResponseEmbedded {
    /// An array of invoice objects. For a complete reference of the invoice object, refer to the [Get invoice endpoint](get-invoice) documentation.
    #[serde(rename = "invoices")]
    pub invoices: Vec<models::ListEntityInvoice>,
}

impl ListInvoices200ResponseEmbedded {
    pub fn new(invoices: Vec<models::ListEntityInvoice>) -> ListInvoices200ResponseEmbedded {
        ListInvoices200ResponseEmbedded {
            invoices,
        }
    }
}

