/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListMethods200ResponseLinks {
    #[serde(rename = "self")]
    pub param_self: models::Url,
    #[serde(rename = "documentation")]
    pub documentation: models::Url,
}

impl ListMethods200ResponseLinks {
    pub fn new(param_self: models::Url, documentation: models::Url) -> ListMethods200ResponseLinks {
        ListMethods200ResponseLinks {
            param_self,
            documentation,
        }
    }
}

