/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEntityUnmatchedCreditTransfer {
    /// Indicates the response contains an unmatched credit transfer object. Will always contain the string `unmatched-credit-transfer` for this endpoint.
    #[serde(rename = "resource")]
    pub resource: String,
    /// The identifier uniquely referring to this unmatched credit transfer.
    #[serde(rename = "id")]
    pub id: String,
    /// The identifier referring to the [profile](get-profile) this entity belongs to.  Most API credentials are linked to a single profile. In these cases the `profileId` can be omitted in the creation request. For organization-level credentials such as OAuth access tokens however, the `profileId` parameter is required.
    #[serde(rename = "profileId")]
    pub profile_id: String,
    #[serde(rename = "amount")]
    pub amount: models::Amount,
    #[serde(rename = "source")]
    pub source: models::EntityUnmatchedCreditTransferSource,
    #[serde(rename = "remittanceInformation")]
    pub remittance_information: models::EntityUnmatchedCreditTransferRemittanceInformation,
    /// The status of the unmatched credit transfer.
    #[serde(rename = "status")]
    pub status: models::UnmatchedCreditTransferStatus,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The date and time at which the unmatched credit transfer expires, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
    /// The IDs of the payments this credit transfer was matched to. Only present when the status is `matched`.
    #[serde(rename = "paymentIds", skip_serializing_if = "Option::is_none")]
    pub payment_ids: Option<Vec<String>>,
    #[serde(rename = "_links")]
    pub _links: models::ListEntityUnmatchedCreditTransferLinks,
}

impl ListEntityUnmatchedCreditTransfer {
    pub fn new(resource: String, id: String, profile_id: String, amount: models::Amount, source: models::EntityUnmatchedCreditTransferSource, remittance_information: models::EntityUnmatchedCreditTransferRemittanceInformation, status: models::UnmatchedCreditTransferStatus, created_at: String, expires_at: String, _links: models::ListEntityUnmatchedCreditTransferLinks) -> ListEntityUnmatchedCreditTransfer {
        ListEntityUnmatchedCreditTransfer {
            resource,
            id,
            profile_id,
            amount,
            source,
            remittance_information,
            status,
            created_at,
            expires_at,
            payment_ids: None,
            _links,
        }
    }
}

