/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListPermissions200ResponseEmbedded {
    /// An array of permission objects.
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<models::EntityPermission>>,
}

impl ListPermissions200ResponseEmbedded {
    pub fn new() -> ListPermissions200ResponseEmbedded {
        ListPermissions200ResponseEmbedded {
            permissions: None,
        }
    }
}

