/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListTerminals200ResponseEmbedded {
    /// An array of terminal objects.
    #[serde(rename = "terminals", skip_serializing_if = "Option::is_none")]
    pub terminals: Option<Vec<models::ListEntityTerminal>>,
}

impl ListTerminals200ResponseEmbedded {
    pub fn new() -> ListTerminals200ResponseEmbedded {
        ListTerminals200ResponseEmbedded {
            terminals: None,
        }
    }
}

