/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListCaptures200ResponseEmbedded {
    /// An array of capture objects.
    #[serde(rename = "captures")]
    pub captures: Vec<models::ListCaptureResponse>,
}

impl ListCaptures200ResponseEmbedded {
    pub fn new(captures: Vec<models::ListCaptureResponse>) -> ListCaptures200ResponseEmbedded {
        ListCaptures200ResponseEmbedded {
            captures,
        }
    }
}

