/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSettlementRefunds200ResponseEmbedded {
    /// An array of refund objects.
    #[serde(rename = "refunds")]
    pub refunds: Vec<models::ListSettlementRefundResponse>,
}

impl ListSettlementRefunds200ResponseEmbedded {
    pub fn new(refunds: Vec<models::ListSettlementRefundResponse>) -> ListSettlementRefunds200ResponseEmbedded {
        ListSettlementRefunds200ResponseEmbedded {
            refunds,
        }
    }
}

