/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListEntityUnmatchedCreditTransferLinks : Links to related resources.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEntityUnmatchedCreditTransferLinks {
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<models::EntityUnmatchedCreditTransferLinksSelf>,
}

impl ListEntityUnmatchedCreditTransferLinks {
    /// Links to related resources.
    pub fn new() -> ListEntityUnmatchedCreditTransferLinks {
        ListEntityUnmatchedCreditTransferLinks {
            param_self: None,
        }
    }
}

