/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListPermissions200ResponseEmbedded {
    /// An array of permission objects.
    #[serde(rename = "permissions")]
    pub permissions: Vec<models::ListEntityPermission>,
}

impl ListPermissions200ResponseEmbedded {
    pub fn new(permissions: Vec<models::ListEntityPermission>) -> ListPermissions200ResponseEmbedded {
        ListPermissions200ResponseEmbedded {
            permissions,
        }
    }
}

