/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAllSubscriptions200ResponseEmbedded {
    /// A list of subscription objects.
    #[serde(rename = "subscriptions", skip_serializing_if = "Option::is_none")]
    pub subscriptions: Option<Vec<models::SubscriptionResponse>>,
}

impl ListAllSubscriptions200ResponseEmbedded {
    pub fn new() -> ListAllSubscriptions200ResponseEmbedded {
        ListAllSubscriptions200ResponseEmbedded {
            subscriptions: None,
        }
    }
}

