/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListConnectBalanceTransfers200ResponseEmbedded {
    /// A list of Connect balance transfers.
    #[serde(rename = "connect_balance_transfers")]
    pub connect_balance_transfers: Vec<models::EntityBalanceTransferResponse>,
}

impl ListConnectBalanceTransfers200ResponseEmbedded {
    pub fn new(connect_balance_transfers: Vec<models::EntityBalanceTransferResponse>) -> ListConnectBalanceTransfers200ResponseEmbedded {
        ListConnectBalanceTransfers200ResponseEmbedded {
            connect_balance_transfers,
        }
    }
}

