/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListClients200ResponseEmbeddedClientsInnerAllOfEmbedded {
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<Box<models::EntityOrganization>>,
    #[serde(rename = "onboarding", skip_serializing_if = "Option::is_none")]
    pub onboarding: Option<Box<models::EntityOnboardingStatus>>,
    #[serde(rename = "capabilities", skip_serializing_if = "Option::is_none")]
    pub capabilities: Option<Box<models::EntityCapability>>,
}

impl ListClients200ResponseEmbeddedClientsInnerAllOfEmbedded {
    pub fn new() -> ListClients200ResponseEmbeddedClientsInnerAllOfEmbedded {
        ListClients200ResponseEmbeddedClientsInnerAllOfEmbedded {
            organization: None,
            onboarding: None,
            capabilities: None,
        }
    }
}

