/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSettlementPayments200Response {
    /// The number of items in this result set. If more items are available, a `_links.next` URL will be present in the result as well.  The maximum number of items per result set is controlled by the `limit` property provided in the request. The default limit is 50 items.
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "_embedded")]
    pub _embedded: Box<models::ListSettlementPayments200ResponseEmbedded>,
    #[serde(rename = "_links")]
    pub _links: Box<models::ListLinks>,
}

impl ListSettlementPayments200Response {
    pub fn new(count: i32, _embedded: models::ListSettlementPayments200ResponseEmbedded, _links: models::ListLinks) -> ListSettlementPayments200Response {
        ListSettlementPayments200Response {
            count,
            _embedded: Box::new(_embedded),
            _links: Box::new(_links),
        }
    }
}

