/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListMandates200ResponseEmbedded {
    /// An array of mandate objects.
    #[serde(rename = "mandates")]
    pub mandates: Vec<models::MandateResponse>,
}

impl ListMandates200ResponseEmbedded {
    pub fn new(mandates: Vec<models::MandateResponse>) -> ListMandates200ResponseEmbedded {
        ListMandates200ResponseEmbedded {
            mandates,
        }
    }
}

