/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListPaymentLinks200ResponseEmbedded {
    /// An array of payment link objects.
    #[serde(rename = "payment_links", skip_serializing_if = "Option::is_none")]
    pub payment_links: Option<Vec<models::PaymentLinkResponse>>,
}

impl ListPaymentLinks200ResponseEmbedded {
    pub fn new() -> ListPaymentLinks200ResponseEmbedded {
        ListPaymentLinks200ResponseEmbedded {
            payment_links: None,
        }
    }
}

