/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListBalances200ResponseEmbedded {
    /// An array of balance objects. For a complete reference of the balance object, refer to the [Get balance endpoint](get-balance) documentation.
    #[serde(rename = "balances")]
    pub balances: Vec<models::ListEntityBalance>,
}

impl ListBalances200ResponseEmbedded {
    pub fn new(balances: Vec<models::ListEntityBalance>) -> ListBalances200ResponseEmbedded {
        ListBalances200ResponseEmbedded {
            balances,
        }
    }
}

