/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListPermissions200ResponseLinks : An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListPermissions200ResponseLinks {
    /// The URL to the current set of items.
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<Box<models::Url>>,
    #[serde(rename = "documentation", skip_serializing_if = "Option::is_none")]
    pub documentation: Option<Box<models::Url>>,
}

impl ListPermissions200ResponseLinks {
    /// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
    pub fn new() -> ListPermissions200ResponseLinks {
        ListPermissions200ResponseLinks {
            param_self: None,
            documentation: None,
        }
    }
}

