/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListEntityMandateLinks : An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEntityMandateLinks {
    #[serde(rename = "self")]
    pub param_self: models::Url,
    /// The API resource URL of the [customer](get-customer) that this mandate belongs to.
    #[serde(rename = "customer")]
    pub customer: models::Url,
}

impl ListEntityMandateLinks {
    /// An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
    pub fn new(param_self: models::Url, customer: models::Url) -> ListEntityMandateLinks {
        ListEntityMandateLinks {
            param_self,
            customer,
        }
    }
}

