/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListCustomers200ResponseEmbedded {
    /// An array of customer objects.
    #[serde(rename = "customers")]
    pub customers: Vec<models::CustomerResponse>,
}

impl ListCustomers200ResponseEmbedded {
    pub fn new(customers: Vec<models::CustomerResponse>) -> ListCustomers200ResponseEmbedded {
        ListCustomers200ResponseEmbedded {
            customers,
        }
    }
}

