/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListMethods200ResponseEmbedded {
    /// An array of payment method objects. For a complete reference of the payment method object, refer to the [Get payment method endpoint](get-method) documentation.
    #[serde(rename = "methods")]
    pub methods: Vec<models::ListEntityMethod>,
}

impl ListMethods200ResponseEmbedded {
    pub fn new(methods: Vec<models::ListEntityMethod>) -> ListMethods200ResponseEmbedded {
        ListMethods200ResponseEmbedded {
            methods,
        }
    }
}

