/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MandateScopes : An array defining the eligible use cases for the mandate. For creditcard mandates, this field will always be  present and can contain one or both of the following values:
/// An array defining the eligible use cases for the mandate. For creditcard mandates, this field will always be  present and can contain one or both of the following values:
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MandateScopes {
    #[serde(rename = "customer-present")]
    CustomerPresent,
    #[serde(rename = "customer-not-present")]
    CustomerNotPresent,

}

impl std::fmt::Display for MandateScopes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CustomerPresent => write!(f, "customer-present"),
            Self::CustomerNotPresent => write!(f, "customer-not-present"),
        }
    }
}

impl Default for MandateScopes {
    fn default() -> MandateScopes {
        Self::CustomerPresent
    }
}

