/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MandateDetailsCardLabel : The card's label. Available for card mandates, if the card label could be detected.
/// The card's label. Available for card mandates, if the card label could be detected.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MandateDetailsCardLabel {
    #[serde(rename = "American Express")]
    AmericanExpress,
    #[serde(rename = "Carta Si")]
    CartaSi,
    #[serde(rename = "Carte Bleue")]
    CarteBleue,
    #[serde(rename = "Dankort")]
    Dankort,
    #[serde(rename = "Diners Club")]
    DinersClub,
    #[serde(rename = "Discover")]
    Discover,
    #[serde(rename = "JCB")]
    Jcb,
    #[serde(rename = "Laser")]
    Laser,
    #[serde(rename = "Maestro")]
    Maestro,
    #[serde(rename = "Mastercard")]
    Mastercard,
    #[serde(rename = "Unionpay")]
    Unionpay,
    #[serde(rename = "Visa")]
    Visa,

}

impl std::fmt::Display for MandateDetailsCardLabel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AmericanExpress => write!(f, "American Express"),
            Self::CartaSi => write!(f, "Carta Si"),
            Self::CarteBleue => write!(f, "Carte Bleue"),
            Self::Dankort => write!(f, "Dankort"),
            Self::DinersClub => write!(f, "Diners Club"),
            Self::Discover => write!(f, "Discover"),
            Self::Jcb => write!(f, "JCB"),
            Self::Laser => write!(f, "Laser"),
            Self::Maestro => write!(f, "Maestro"),
            Self::Mastercard => write!(f, "Mastercard"),
            Self::Unionpay => write!(f, "Unionpay"),
            Self::Visa => write!(f, "Visa"),
        }
    }
}

impl Default for MandateDetailsCardLabel {
    fn default() -> MandateDetailsCardLabel {
        Self::AmericanExpress
    }
}

