/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MandateMethodResponse : Payment method of the mandate.  SEPA Direct Debit and PayPal mandates can be created directly.
/// Payment method of the mandate.  SEPA Direct Debit and PayPal mandates can be created directly.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MandateMethodResponse {
    #[serde(rename = "creditcard")]
    Creditcard,
    #[serde(rename = "directdebit")]
    Directdebit,
    #[serde(rename = "paypal")]
    Paypal,

}

impl std::fmt::Display for MandateMethodResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Creditcard => write!(f, "creditcard"),
            Self::Directdebit => write!(f, "directdebit"),
            Self::Paypal => write!(f, "paypal"),
        }
    }
}

impl Default for MandateMethodResponse {
    fn default() -> MandateMethodResponse {
        Self::Creditcard
    }
}

