/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MethodIssuerStatus : The status of the issuer. If the status is `pending-issuer`, an additional action from your side may be required with the issuer.
/// The status of the issuer. If the status is `pending-issuer`, an additional action from your side may be required with the issuer.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MethodIssuerStatus {
    #[serde(rename = "activated")]
    Activated,
    #[serde(rename = "pending-issuer")]
    PendingIssuer,

}

impl std::fmt::Display for MethodIssuerStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Activated => write!(f, "activated"),
            Self::PendingIssuer => write!(f, "pending-issuer"),
        }
    }
}

impl Default for MethodIssuerStatus {
    fn default() -> MethodIssuerStatus {
        Self::Activated
    }
}

