/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnboardingStatus : The current status of the organization's onboarding process.
/// The current status of the organization's onboarding process.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OnboardingStatus {
    #[serde(rename = "needs-data")]
    NeedsData,
    #[serde(rename = "in-review")]
    InReview,
    #[serde(rename = "completed")]
    Completed,

}

impl std::fmt::Display for OnboardingStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NeedsData => write!(f, "needs-data"),
            Self::InReview => write!(f, "in-review"),
            Self::Completed => write!(f, "completed"),
        }
    }
}

impl Default for OnboardingStatus {
    fn default() -> OnboardingStatus {
        Self::NeedsData
    }
}

