/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrganizationVatRegulation : Mollie applies Dutch VAT for merchants based in The Netherlands, British VAT for merchants based in The United Kingdom, and shifted VAT for merchants in the European Union.  The field is not present for merchants residing in other countries.
/// Mollie applies Dutch VAT for merchants based in The Netherlands, British VAT for merchants based in The United Kingdom, and shifted VAT for merchants in the European Union.  The field is not present for merchants residing in other countries.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrganizationVatRegulation {
    #[serde(rename = "dutch")]
    Dutch,
    #[serde(rename = "british")]
    British,
    #[serde(rename = "shifted")]
    Shifted,

}

impl std::fmt::Display for OrganizationVatRegulation {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Dutch => write!(f, "dutch"),
            Self::British => write!(f, "british"),
            Self::Shifted => write!(f, "shifted"),
        }
    }
}

impl Default for OrganizationVatRegulation {
    fn default() -> OrganizationVatRegulation {
        Self::Dutch
    }
}

