/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentMethod : The payment method, if applicable
/// The payment method, if applicable
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentMethod {
    #[serde(rename = "alma")]
    Alma,
    #[serde(rename = "bacs")]
    Bacs,
    #[serde(rename = "applepay")]
    Applepay,
    #[serde(rename = "bancomatpay")]
    Bancomatpay,
    #[serde(rename = "bancontact")]
    Bancontact,
    #[serde(rename = "banktransfer")]
    Banktransfer,
    #[serde(rename = "belfius")]
    Belfius,
    #[serde(rename = "billie")]
    Billie,
    #[serde(rename = "bizum")]
    Bizum,
    #[serde(rename = "bitcoin")]
    Bitcoin,
    #[serde(rename = "blik")]
    Blik,
    #[serde(rename = "creditcard")]
    Creditcard,
    #[serde(rename = "directdebit")]
    Directdebit,
    #[serde(rename = "eps")]
    Eps,
    #[serde(rename = "giftcard")]
    Giftcard,
    #[serde(rename = "giropay")]
    Giropay,
    #[serde(rename = "googlepay")]
    Googlepay,
    #[serde(rename = "ideal")]
    Ideal,
    #[serde(rename = "in3")]
    In3,
    #[serde(rename = "inghomepay")]
    Inghomepay,
    #[serde(rename = "kbc")]
    Kbc,
    #[serde(rename = "klarnapaylater")]
    Klarnapaylater,
    #[serde(rename = "klarnapaynow")]
    Klarnapaynow,
    #[serde(rename = "klarnasliceit")]
    Klarnasliceit,
    #[serde(rename = "klarna")]
    Klarna,
    #[serde(rename = "mbway")]
    Mbway,
    #[serde(rename = "mobilepay")]
    Mobilepay,
    #[serde(rename = "multibanco")]
    Multibanco,
    #[serde(rename = "mybank")]
    Mybank,
    #[serde(rename = "paybybank")]
    Paybybank,
    #[serde(rename = "payconiq")]
    Payconiq,
    #[serde(rename = "paypal")]
    Paypal,
    #[serde(rename = "paysafecard")]
    Paysafecard,
    #[serde(rename = "przelewy24")]
    Przelewy24,
    #[serde(rename = "riverty")]
    Riverty,
    #[serde(rename = "satispay")]
    Satispay,
    #[serde(rename = "podiumcadeaukaart")]
    Podiumcadeaukaart,
    #[serde(rename = "pointofsale")]
    Pointofsale,
    #[serde(rename = "sofort")]
    Sofort,
    #[serde(rename = "swish")]
    Swish,
    #[serde(rename = "trustly")]
    Trustly,
    #[serde(rename = "twint")]
    Twint,
    #[serde(rename = "vipps")]
    Vipps,
    #[serde(rename = "voucher")]
    Voucher,

}

impl std::fmt::Display for PaymentMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Alma => write!(f, "alma"),
            Self::Bacs => write!(f, "bacs"),
            Self::Applepay => write!(f, "applepay"),
            Self::Bancomatpay => write!(f, "bancomatpay"),
            Self::Bancontact => write!(f, "bancontact"),
            Self::Banktransfer => write!(f, "banktransfer"),
            Self::Belfius => write!(f, "belfius"),
            Self::Billie => write!(f, "billie"),
            Self::Bizum => write!(f, "bizum"),
            Self::Bitcoin => write!(f, "bitcoin"),
            Self::Blik => write!(f, "blik"),
            Self::Creditcard => write!(f, "creditcard"),
            Self::Directdebit => write!(f, "directdebit"),
            Self::Eps => write!(f, "eps"),
            Self::Giftcard => write!(f, "giftcard"),
            Self::Giropay => write!(f, "giropay"),
            Self::Googlepay => write!(f, "googlepay"),
            Self::Ideal => write!(f, "ideal"),
            Self::In3 => write!(f, "in3"),
            Self::Inghomepay => write!(f, "inghomepay"),
            Self::Kbc => write!(f, "kbc"),
            Self::Klarnapaylater => write!(f, "klarnapaylater"),
            Self::Klarnapaynow => write!(f, "klarnapaynow"),
            Self::Klarnasliceit => write!(f, "klarnasliceit"),
            Self::Klarna => write!(f, "klarna"),
            Self::Mbway => write!(f, "mbway"),
            Self::Mobilepay => write!(f, "mobilepay"),
            Self::Multibanco => write!(f, "multibanco"),
            Self::Mybank => write!(f, "mybank"),
            Self::Paybybank => write!(f, "paybybank"),
            Self::Payconiq => write!(f, "payconiq"),
            Self::Paypal => write!(f, "paypal"),
            Self::Paysafecard => write!(f, "paysafecard"),
            Self::Przelewy24 => write!(f, "przelewy24"),
            Self::Riverty => write!(f, "riverty"),
            Self::Satispay => write!(f, "satispay"),
            Self::Podiumcadeaukaart => write!(f, "podiumcadeaukaart"),
            Self::Pointofsale => write!(f, "pointofsale"),
            Self::Sofort => write!(f, "sofort"),
            Self::Swish => write!(f, "swish"),
            Self::Trustly => write!(f, "trustly"),
            Self::Twint => write!(f, "twint"),
            Self::Vipps => write!(f, "vipps"),
            Self::Voucher => write!(f, "voucher"),
        }
    }
}

impl Default for PaymentMethod {
    fn default() -> PaymentMethod {
        Self::Alma
    }
}

