/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentLinkSequenceTypeResponse {
    #[serde(rename = "oneoff")]
    Oneoff,
    #[serde(rename = "first")]
    First,

}

impl std::fmt::Display for PaymentLinkSequenceTypeResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Oneoff => write!(f, "oneoff"),
            Self::First => write!(f, "first"),
        }
    }
}

impl Default for PaymentLinkSequenceTypeResponse {
    fn default() -> PaymentLinkSequenceTypeResponse {
        Self::Oneoff
    }
}

