/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentDetailsWallet : The wallet used when creating the payment.
/// The wallet used when creating the payment.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentDetailsWallet {
    #[serde(rename = "applepay")]
    Applepay,

}

impl std::fmt::Display for PaymentDetailsWallet {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Applepay => write!(f, "applepay"),
        }
    }
}

impl Default for PaymentDetailsWallet {
    fn default() -> PaymentDetailsWallet {
        Self::Applepay
    }
}

