/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentDetailsCardAudition : The card's target audience, if known.
/// The card's target audience, if known.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentDetailsCardAudition {
    #[serde(rename = "consumer")]
    Consumer,
    #[serde(rename = "business")]
    Business,

}

impl std::fmt::Display for PaymentDetailsCardAudition {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Consumer => write!(f, "consumer"),
            Self::Business => write!(f, "business"),
        }
    }
}

impl Default for PaymentDetailsCardAudition {
    fn default() -> PaymentDetailsCardAudition {
        Self::Consumer
    }
}

