/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentDetailsSellerProtectionResponse : Indicates to what extent the payment is eligible for PayPal's Seller Protection. Only available for PayPal payments, and if the information is made available by PayPal.
/// Indicates to what extent the payment is eligible for PayPal's Seller Protection. Only available for PayPal payments, and if the information is made available by PayPal.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentDetailsSellerProtectionResponse {
    #[serde(rename = "Eligible")]
    Eligible,
    #[serde(rename = "Ineligible")]
    Ineligible,
    #[serde(rename = "Partially Eligible - INR Only")]
    PartiallyEligibleInrOnly,
    #[serde(rename = "Partially Eligible - Unauth Only")]
    PartiallyEligibleUnauthOnly,
    #[serde(rename = "Partially Eligible")]
    PartiallyEligible,
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Active")]
    Active,
    #[serde(rename = "Fraud Control - Unauth Premium Eligible")]
    FraudControlUnauthPremiumEligible,

}

impl std::fmt::Display for PaymentDetailsSellerProtectionResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Eligible => write!(f, "Eligible"),
            Self::Ineligible => write!(f, "Ineligible"),
            Self::PartiallyEligibleInrOnly => write!(f, "Partially Eligible - INR Only"),
            Self::PartiallyEligibleUnauthOnly => write!(f, "Partially Eligible - Unauth Only"),
            Self::PartiallyEligible => write!(f, "Partially Eligible"),
            Self::None => write!(f, "None"),
            Self::Active => write!(f, "Active"),
            Self::FraudControlUnauthPremiumEligible => write!(f, "Fraud Control - Unauth Premium Eligible"),
        }
    }
}

impl Default for PaymentDetailsSellerProtectionResponse {
    fn default() -> PaymentDetailsSellerProtectionResponse {
        Self::Eligible
    }
}

