/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentDetailsCardSecurityResponse : The level of security applied during card processing.
/// The level of security applied during card processing.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentDetailsCardSecurityResponse {
    #[serde(rename = "normal")]
    Normal,
    #[serde(rename = "3dsecure")]
    Variant3dsecure,

}

impl std::fmt::Display for PaymentDetailsCardSecurityResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Normal => write!(f, "normal"),
            Self::Variant3dsecure => write!(f, "3dsecure"),
        }
    }
}

impl Default for PaymentDetailsCardSecurityResponse {
    fn default() -> PaymentDetailsCardSecurityResponse {
        Self::Normal
    }
}

