/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RefundRoutingReversalsSourceType : The type of source. Currently only the source type `organization` is supported.
/// The type of source. Currently only the source type `organization` is supported.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RefundRoutingReversalsSourceType {
    #[serde(rename = "organization")]
    Organization,

}

impl std::fmt::Display for RefundRoutingReversalsSourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Organization => write!(f, "organization"),
        }
    }
}

impl Default for RefundRoutingReversalsSourceType {
    fn default() -> RefundRoutingReversalsSourceType {
        Self::Organization
    }
}

