/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RouteCreateRequestDestination : The destination of the route.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteCreateRequestDestination {
    #[serde(rename = "type")]
    pub r#type: models::RouteDestinationType,
    /// Required for destination type `organization`. The ID of the connected organization the funds should be routed to.
    #[serde(rename = "organizationId")]
    pub organization_id: String,
}

impl RouteCreateRequestDestination {
    /// The destination of the route.
    pub fn new(r#type: models::RouteDestinationType, organization_id: String) -> RouteCreateRequestDestination {
        RouteCreateRequestDestination {
            r#type,
            organization_id,
        }
    }
}

