/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteCreateResponse {
    /// Indicates the response contains a route object. Will always contain the string `route` for this endpoint.
    #[serde(rename = "resource")]
    pub resource: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "paymentId")]
    pub payment_id: String,
    /// The amount of the route. That amount that will be routed to the specified destination.
    #[serde(rename = "amount")]
    pub amount: models::Amount,
    /// The description of the route. This description is shown in the reports.
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "destination")]
    pub destination: models::EntityRouteDestination,
    /// Whether to create the entity in test mode or live mode.  Most API credentials are specifically created for either live mode or test mode, in which case this parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
    #[serde(rename = "testmode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub testmode: Option<Option<bool>>,
    #[serde(rename = "_links")]
    pub _links: models::EntityWebhookLinks,
}

impl RouteCreateResponse {
    pub fn new(resource: String, id: String, payment_id: String, amount: models::Amount, description: String, destination: models::EntityRouteDestination, _links: models::EntityWebhookLinks) -> RouteCreateResponse {
        RouteCreateResponse {
            resource,
            id,
            payment_id,
            amount,
            description,
            destination,
            testmode: None,
            _links,
        }
    }
}

