/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SalesInvoiceRecipientLocaleResponse : The locale for the recipient, to be used for translations in PDF generation and payment pages.
/// The locale for the recipient, to be used for translations in PDF generation and payment pages.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SalesInvoiceRecipientLocaleResponse {
    #[serde(rename = "en_US")]
    EnUs,
    #[serde(rename = "en_GB")]
    EnGb,
    #[serde(rename = "nl_NL")]
    NlNl,
    #[serde(rename = "nl_BE")]
    NlBe,
    #[serde(rename = "de_DE")]
    DeDe,
    #[serde(rename = "de_AT")]
    DeAt,
    #[serde(rename = "de_CH")]
    DeCh,
    #[serde(rename = "fr_FR")]
    FrFr,
    #[serde(rename = "fr_BE")]
    FrBe,

}

impl std::fmt::Display for SalesInvoiceRecipientLocaleResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::EnUs => write!(f, "en_US"),
            Self::EnGb => write!(f, "en_GB"),
            Self::NlNl => write!(f, "nl_NL"),
            Self::NlBe => write!(f, "nl_BE"),
            Self::DeDe => write!(f, "de_DE"),
            Self::DeAt => write!(f, "de_AT"),
            Self::DeCh => write!(f, "de_CH"),
            Self::FrFr => write!(f, "fr_FR"),
            Self::FrBe => write!(f, "fr_BE"),
        }
    }
}

impl Default for SalesInvoiceRecipientLocaleResponse {
    fn default() -> SalesInvoiceRecipientLocaleResponse {
        Self::EnUs
    }
}

