/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SalesInvoiceRecipientType : The type of recipient, either `consumer` or `business`. This will determine what further fields are required on the `recipient` object.
/// The type of recipient, either `consumer` or `business`. This will determine what further fields are required on the `recipient` object.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SalesInvoiceRecipientType {
    #[serde(rename = "consumer")]
    Consumer,
    #[serde(rename = "business")]
    Business,

}

impl std::fmt::Display for SalesInvoiceRecipientType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Consumer => write!(f, "consumer"),
            Self::Business => write!(f, "business"),
        }
    }
}

impl Default for SalesInvoiceRecipientType {
    fn default() -> SalesInvoiceRecipientType {
        Self::Consumer
    }
}

