/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SalesInvoiceLineItem {
    /// A description of the line item. For example *LEGO 4440 Forest Police Station*.
    #[serde(rename = "description")]
    pub description: String,
    /// The number of items.
    #[serde(rename = "quantity")]
    pub quantity: i32,
    /// The vat rate to be applied to this line item.
    #[serde(rename = "vatRate")]
    pub vat_rate: String,
    /// The price of a single item excluding VAT.  For example: `{\"currency\":\"EUR\", \"value\":\"89.00\"}` if the box of LEGO costs €89.00 each.  The unit price can be zero in case of free items.
    #[serde(rename = "unitPrice")]
    pub unit_price: models::Amount,
    /// The discount to be applied to the line item.
    #[serde(rename = "discount", skip_serializing_if = "Option::is_none")]
    pub discount: Option<models::SalesInvoiceDiscount>,
}

impl SalesInvoiceLineItem {
    pub fn new(description: String, quantity: i32, vat_rate: String, unit_price: models::Amount) -> SalesInvoiceLineItem {
        SalesInvoiceLineItem {
            description,
            quantity,
            vat_rate,
            unit_price,
            discount: None,
        }
    }
}

