/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SalesInvoicePaymentDetails {
    #[serde(rename = "source")]
    pub source: models::SalesInvoicePaymentDetailsSource,
    /// A reference to the payment the sales invoice is paid by. Required for `source` values `payment-link` and `payment`.
    #[serde(rename = "sourceReference", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source_reference: Option<Option<String>>,
}

impl SalesInvoicePaymentDetails {
    pub fn new(source: models::SalesInvoicePaymentDetailsSource) -> SalesInvoicePaymentDetails {
        SalesInvoicePaymentDetails {
            source,
            source_reference: None,
        }
    }
}

