/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusHistoryEntryResponse : Represents an entry in the transfer's status history, recording a past status transition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusHistoryEntryResponse {
    /// The status that the transfer transitioned to.
    #[serde(rename = "status")]
    pub status: models::TransferStatus,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "statusReason", skip_serializing_if = "Option::is_none")]
    pub status_reason: Option<models::StatusReason2>,
}

impl StatusHistoryEntryResponse {
    /// Represents an entry in the transfer's status history, recording a past status transition.
    pub fn new(status: models::TransferStatus, created_at: String) -> StatusHistoryEntryResponse {
        StatusHistoryEntryResponse {
            status,
            created_at,
            status_reason: None,
        }
    }
}

