/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubTotals2 {
    #[serde(rename = "sub-totals", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sub_totals: Option<Option<Vec<models::SubTotals>>>,
    /// Number of transactions of this type
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Payment type of the transactions
    #[serde(rename = "method", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub method: Option<Option<models::PaymentMethod>>,
    /// In case of payments transactions with card, the card issuer will be available
    #[serde(rename = "cardIssuer", skip_serializing_if = "Option::is_none")]
    pub card_issuer: Option<models::BalanceCardIssuer>,
    /// In case of payments trnsactions with card, the card audience will be available.
    #[serde(rename = "cardAudience", skip_serializing_if = "Option::is_none")]
    pub card_audience: Option<models::BalanceCardAudience>,
    /// In case of payments transactions with card, the card region will be available.
    #[serde(rename = "cardRegion", skip_serializing_if = "Option::is_none")]
    pub card_region: Option<models::BalanceCardRegion>,
    /// Present when the transaction represents a fee.
    #[serde(rename = "feeType", skip_serializing_if = "Option::is_none")]
    pub fee_type: Option<models::BalanceFeeType>,
    /// Prepayment part: fee itself, reimbursement, discount, VAT or rounding compensation.
    #[serde(rename = "prepaymentPartType", skip_serializing_if = "Option::is_none")]
    pub prepayment_part_type: Option<models::BalancePrepaymentPartType>,
    /// Represents the transaction type
    #[serde(rename = "transactionType", skip_serializing_if = "Option::is_none")]
    pub transaction_type: Option<models::BalanceTransactionType>,
}

impl SubTotals2 {
    pub fn new() -> SubTotals2 {
        SubTotals2 {
            sub_totals: None,
            count: None,
            method: None,
            card_issuer: None,
            card_audience: None,
            card_region: None,
            fee_type: None,
            prepayment_part_type: None,
            transaction_type: None,
        }
    }
}

