/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubscriptionStatusResponse : The subscription's current status is directly related to the status of the underlying customer or mandate that is enabling the subscription.
/// The subscription's current status is directly related to the status of the underlying customer or mandate that is enabling the subscription.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubscriptionStatusResponse {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "canceled")]
    Canceled,
    #[serde(rename = "suspended")]
    Suspended,
    #[serde(rename = "completed")]
    Completed,

}

impl std::fmt::Display for SubscriptionStatusResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pending => write!(f, "pending"),
            Self::Active => write!(f, "active"),
            Self::Canceled => write!(f, "canceled"),
            Self::Suspended => write!(f, "suspended"),
            Self::Completed => write!(f, "completed"),
        }
    }
}

impl Default for SubscriptionStatusResponse {
    fn default() -> SubscriptionStatusResponse {
        Self::Pending
    }
}

