/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionResponse {
    /// Indicates the response contains a subscription object. Will always contain the string `subscription` for this endpoint.
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::Mode>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::SubscriptionStatus>,
    /// The amount for each individual payment that is charged with this subscription. For example, for a monthly subscription of €10, the subscription amount should be set to €10.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<models::Amount>,
    /// Total number of payments for the subscription. Once this number of payments is reached, the subscription is considered completed.  Test mode subscriptions will get canceled automatically after 10 payments.
    #[serde(rename = "times", skip_serializing_if = "Option::is_none")]
    pub times: Option<i32>,
    /// Number of payments left for the subscription.
    #[serde(rename = "timesRemaining", skip_serializing_if = "Option::is_none")]
    pub times_remaining: Option<i32>,
    /// Interval to wait between payments, for example `1 month` or `14 days`.  The maximum interval is one year (`12 months`, `52 weeks`, or `365 days`).  Possible values: `... days`, `... weeks`, `... months`.
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<String>,
    /// The start date of the subscription in `YYYY-MM-DD` format.
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    /// The date of the next scheduled payment in `YYYY-MM-DD` format. If the subscription has been completed or canceled, this parameter will not be returned.
    #[serde(rename = "nextPaymentDate", skip_serializing_if = "Option::is_none")]
    pub next_payment_date: Option<String>,
    /// The subscription's description will be used as the description of the resulting individual payments and so showing up on the bank statement of the consumer.  **Please note:** the description needs to be unique for the Customer in case it has multiple active subscriptions.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "method", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub method: Option<Option<models::SubscriptionMethodResponse>>,
    #[serde(rename = "applicationFee", skip_serializing_if = "Option::is_none")]
    pub application_fee: Option<models::EntitySubscriptionApplicationFee>,
    /// Provide any data you like, for example a string or a JSON object. We will save the data alongside the entity. Whenever you fetch the entity with our API, we will also include the metadata. You can use up to approximately 1kB.  Any metadata added to the subscription will be automatically forwarded to the payments generated for it.
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<models::Metadata>>,
    /// We will call this URL for any payment status changes of payments resulting from this subscription.  This webhook will receive **all** events for the subscription's payments. This may include payment failures as well. Be sure to verify the payment's subscription ID and its status.
    #[serde(rename = "webhookUrl", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<String>,
    #[serde(rename = "customerId", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
    #[serde(rename = "mandateId", skip_serializing_if = "Option::is_none")]
    pub mandate_id: Option<String>,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The subscription's date and time of cancellation, in ISO 8601 format. This parameter is omitted if the subscription is not canceled (yet).
    #[serde(rename = "canceledAt", skip_serializing_if = "Option::is_none")]
    pub canceled_at: Option<String>,
    /// Whether to create the entity in test mode or live mode.  Most API credentials are specifically created for either live mode or test mode, in which case this parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
    #[serde(rename = "testmode", skip_serializing_if = "Option::is_none")]
    pub testmode: Option<bool>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<models::EntitySubscriptionLinks>,
}

impl SubscriptionResponse {
    pub fn new() -> SubscriptionResponse {
        SubscriptionResponse {
            resource: None,
            id: None,
            mode: None,
            status: None,
            amount: None,
            times: None,
            times_remaining: None,
            interval: None,
            start_date: None,
            next_payment_date: None,
            description: None,
            method: None,
            application_fee: None,
            metadata: None,
            webhook_url: None,
            customer_id: None,
            mandate_id: None,
            created_at: None,
            canceled_at: None,
            testmode: None,
            _links: None,
        }
    }
}

