/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TerminalBrand : The brand of the terminal.
/// The brand of the terminal.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TerminalBrand {
    #[serde(rename = "PAX")]
    Pax,
    #[serde(rename = "Tap")]
    Tap,

}

impl std::fmt::Display for TerminalBrand {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pax => write!(f, "PAX"),
            Self::Tap => write!(f, "Tap"),
        }
    }
}

impl Default for TerminalBrand {
    fn default() -> TerminalBrand {
        Self::Pax
    }
}

