/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TerminalModel : The model of the terminal. For example for a PAX A920, this field's value will be `A920`.
/// The model of the terminal. For example for a PAX A920, this field's value will be `A920`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TerminalModel {
    #[serde(rename = "A35")]
    A35,
    #[serde(rename = "A77")]
    A77,
    #[serde(rename = "A920")]
    A920,
    #[serde(rename = "A920Pro")]
    A920Pro,
    #[serde(rename = "IM30")]
    Im30,
    #[serde(rename = "Tap")]
    Tap,

}

impl std::fmt::Display for TerminalModel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::A35 => write!(f, "A35"),
            Self::A77 => write!(f, "A77"),
            Self::A920 => write!(f, "A920"),
            Self::A920Pro => write!(f, "A920Pro"),
            Self::Im30 => write!(f, "IM30"),
            Self::Tap => write!(f, "Tap"),
        }
    }
}

impl Default for TerminalModel {
    fn default() -> TerminalModel {
        Self::A35
    }
}

