/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferStatus : The status of the transfer.
/// The status of the transfer.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransferStatus {
    #[serde(rename = "requested")]
    Requested,
    #[serde(rename = "initiated")]
    Initiated,
    #[serde(rename = "pending-review")]
    PendingReview,
    #[serde(rename = "processed")]
    Processed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "returned")]
    Returned,

}

impl std::fmt::Display for TransferStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Requested => write!(f, "requested"),
            Self::Initiated => write!(f, "initiated"),
            Self::PendingReview => write!(f, "pending-review"),
            Self::Processed => write!(f, "processed"),
            Self::Failed => write!(f, "failed"),
            Self::Blocked => write!(f, "blocked"),
            Self::Returned => write!(f, "returned"),
        }
    }
}

impl Default for TransferStatus {
    fn default() -> TransferStatus {
        Self::Requested
    }
}

