/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferScheme : The scheme, as requested by the client.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferScheme {
    #[serde(rename = "type")]
    pub r#type: models::TransferSchemeType,
}

impl TransferScheme {
    /// The scheme, as requested by the client.
    pub fn new(r#type: models::TransferSchemeType) -> TransferScheme {
        TransferScheme {
            r#type,
        }
    }
}

