/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionResponse {
    /// Indicates the response contains a business account transaction object. Will always contain the string `business-account-transaction` for this endpoint.
    #[serde(rename = "resource")]
    pub resource: String,
    /// The identifier uniquely referring to this transaction. Mollie assigns this identifier at transaction creation time.
    #[serde(rename = "id")]
    pub id: String,
    /// The identifier of the business account this transaction belongs to.
    #[serde(rename = "businessAccountId")]
    pub business_account_id: String,
    #[serde(rename = "creditDebitIndicator")]
    pub credit_debit_indicator: models::CreditDebitIndicator,
    #[serde(rename = "type")]
    pub r#type: models::TransactionType,
    /// The amount of the transaction, e.g. `{\"currency\":\"EUR\", \"value\":\"100.00\"}`.
    #[serde(rename = "amount")]
    pub amount: models::Amount,
    /// A short description of the transaction.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The counterparty involved in this transaction.
    #[serde(rename = "counterparty", skip_serializing_if = "Option::is_none")]
    pub counterparty: Option<models::Counterparty>,
    /// The balance of the business account after this transaction was processed.
    #[serde(rename = "afterBalance", skip_serializing_if = "Option::is_none")]
    pub after_balance: Option<models::AfterBalance>,
    /// The date and time when the transaction was processed, in ISO 8601 format.
    #[serde(rename = "processedAt", skip_serializing_if = "Option::is_none")]
    pub processed_at: Option<String>,
    #[serde(rename = "mode")]
    pub mode: models::Mode,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl TransactionResponse {
    pub fn new(resource: String, id: String, business_account_id: String, credit_debit_indicator: models::CreditDebitIndicator, r#type: models::TransactionType, amount: models::Amount, mode: models::Mode, created_at: String) -> TransactionResponse {
        TransactionResponse {
            resource,
            id,
            business_account_id,
            credit_debit_indicator,
            r#type,
            amount,
            description: None,
            counterparty: None,
            after_balance: None,
            processed_at: None,
            mode,
            created_at,
        }
    }
}

