/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferRequest {
    /// Indicates the response contains a transfer object. Will always contain the string `business-account-transfer` for this endpoint.
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    /// The identifier uniquely referring to this transfer. Mollie assigns this identifier at transfer creation time.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::Mode>,
    /// The IBAN of the debtor's (sender) Mollie account from which to initiate the transfer.
    #[serde(rename = "debtorIban")]
    pub debtor_iban: String,
    /// The debtor (sender) of the transfer, including their name and account details.
    #[serde(rename = "debtor", skip_serializing_if = "Option::is_none")]
    pub debtor: Option<models::TransferParty>,
    /// The creditor (recipient) of the transfer, including their name and account details.
    #[serde(rename = "creditor")]
    pub creditor: models::TransferParty,
    /// The amount of the transfer, e.g. `{\"currency\":\"EUR\", \"value\":\"100.00\"}` if you would want to transfer €100.00.  Only `EUR` is supported for SEPA transfers.
    #[serde(rename = "amount")]
    pub amount: models::Amount,
    /// A short description of the transfer. This will appear on the bank statement of both the debtor and creditor.  It must begin with an alphanumeric character, followed by any combination of letters, numbers, spaces or special characters `/ - ? : ( ) . , ' + _`.  Constraints: - Cannot be solely a hyphen (-) or colon (:) - Cannot contain consecutive hyphens (--) - Cannot contain consecutive colons (::)
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The identifier of the corresponding transaction in the business accounts transaction resource.
    #[serde(rename = "businessAccountTransactionId", skip_serializing_if = "Option::is_none")]
    pub business_account_transaction_id: Option<String>,
    #[serde(rename = "transferScheme")]
    pub transfer_scheme: models::TransferScheme,
    #[serde(rename = "creditDebitIndicator", skip_serializing_if = "Option::is_none")]
    pub credit_debit_indicator: Option<models::CreditDebitIndicator>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::TransferStatus>,
    /// A chronological list of status transitions the transfer has gone through.
    #[serde(rename = "statusHistory", skip_serializing_if = "Option::is_none")]
    pub status_history: Option<Vec<models::StatusHistoryEntry>>,
    /// The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "statusReason", skip_serializing_if = "Option::is_none")]
    pub status_reason: Option<models::StatusReason2>,
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<models::Metadata>>,
    /// Whether to create the entity in test mode or live mode.  Most API credentials are specifically created for either live mode or test mode, in which case this parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
    #[serde(rename = "testmode", skip_serializing_if = "Option::is_none")]
    pub testmode: Option<bool>,
}

impl TransferRequest {
    pub fn new(debtor_iban: String, creditor: models::TransferParty, amount: models::Amount, transfer_scheme: models::TransferScheme) -> TransferRequest {
        TransferRequest {
            resource: None,
            id: None,
            mode: None,
            debtor_iban,
            debtor: None,
            creditor,
            amount,
            description: None,
            business_account_transaction_id: None,
            transfer_scheme,
            credit_debit_indicator: None,
            status: None,
            status_history: None,
            created_at: None,
            status_reason: None,
            metadata: None,
            testmode: None,
        }
    }
}

