/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionType : Indicates what kind of transaction this is.  We may introduce new transaction types as we expand the product. We recommend building your integration to handle unexpected values gracefully, so nothing breaks when that happens. 
/// Indicates what kind of transaction this is.  We may introduce new transaction types as we expand the product. We recommend building your integration to handle unexpected values gracefully, so nothing breaks when that happens. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionType {
    #[serde(rename = "card-payment")]
    CardPayment,
    #[serde(rename = "bank-transfer")]
    BankTransfer,
    #[serde(rename = "psp-transfer")]
    PspTransfer,
    #[serde(rename = "internal-transfer")]
    InternalTransfer,
    #[serde(rename = "ideal-payment")]
    IdealPayment,
    #[serde(rename = "fee")]
    Fee,
    #[serde(rename = "correction")]
    Correction,
    #[serde(rename = "direct-debit")]
    DirectDebit,
    #[serde(rename = "direct-debit-refund")]
    DirectDebitRefund,

}

impl std::fmt::Display for TransactionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CardPayment => write!(f, "card-payment"),
            Self::BankTransfer => write!(f, "bank-transfer"),
            Self::PspTransfer => write!(f, "psp-transfer"),
            Self::InternalTransfer => write!(f, "internal-transfer"),
            Self::IdealPayment => write!(f, "ideal-payment"),
            Self::Fee => write!(f, "fee"),
            Self::Correction => write!(f, "correction"),
            Self::DirectDebit => write!(f, "direct-debit"),
            Self::DirectDebitRefund => write!(f, "direct-debit-refund"),
        }
    }
}

impl Default for TransactionType {
    fn default() -> TransactionType {
        Self::CardPayment
    }
}

