/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnmatchedCreditTransferActionType {
    #[serde(rename = "match")]
    Match,
    #[serde(rename = "return")]
    Return,

}

impl std::fmt::Display for UnmatchedCreditTransferActionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Match => write!(f, "match"),
            Self::Return => write!(f, "return"),
        }
    }
}

impl Default for UnmatchedCreditTransferActionType {
    fn default() -> UnmatchedCreditTransferActionType {
        Self::Match
    }
}

