/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePaymentLinkRequest {
    /// A short description of the payment link. The description is visible in the Dashboard and will be shown on the customer's bank or card statement when possible.  Updating the description does not affect any previously existing payments created for this payment link.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The minimum amount of the payment link. This property is only allowed when there is no amount provided. The customer will be prompted to enter a value greater than or equal to the minimum amount.
    #[serde(rename = "minimumAmount", skip_serializing_if = "Option::is_none")]
    pub minimum_amount: Option<models::Amount>,
    /// Whether the payment link is archived. Customers will not be able to complete payments on archived payment links.
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
    /// An array of payment methods that are allowed to be used for this payment link. When this parameter is not provided or is an empty array, all enabled payment methods will be available.
    #[serde(rename = "allowedMethods", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allowed_methods: Option<Option<Vec<models::PaymentLinkMethod>>>,
    /// Optionally provide the order lines for the payment. Each line contains details such as a description of the item ordered and its price.  All lines must have the same currency as the payment.  Required for payment methods `billie`, `in3`, `klarna`, `riverty` and `voucher`.
    #[serde(rename = "lines", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lines: Option<Option<Vec<models::PaymentLineItem>>>,
    /// The customer's billing address details. We advise to provide these details to improve fraud protection and conversion.  Should include `email` or a valid postal address consisting of `streetAndNumber`, `postalCode`, `city` and `country`.  Required for payment method `in3`, `klarna`, `billie` and `riverty`.
    #[serde(rename = "billingAddress", skip_serializing_if = "Option::is_none")]
    pub billing_address: Option<models::PaymentAddress>,
    /// The customer's shipping address details. We advise to provide these details to improve fraud protection and conversion.  Should include `email` or a valid postal address consisting of `streetAndNumber`, `postalCode`, `city` and `country`.
    #[serde(rename = "shippingAddress", skip_serializing_if = "Option::is_none")]
    pub shipping_address: Option<models::PaymentAddress>,
    /// Whether the entity was created in test mode or live mode. This field does not update the mode of the entity.  Most API credentials are specifically created for either live mode or test mode, in which case this parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
    #[serde(rename = "testmode", skip_serializing_if = "Option::is_none")]
    pub testmode: Option<bool>,
}

impl UpdatePaymentLinkRequest {
    pub fn new() -> UpdatePaymentLinkRequest {
        UpdatePaymentLinkRequest {
            description: None,
            minimum_amount: None,
            archived: None,
            allowed_methods: None,
            lines: None,
            billing_address: None,
            shipping_address: None,
            testmode: None,
        }
    }
}

