/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProfileRequest {
    /// The profile's name, this will usually reflect the trade name or brand name of the profile's website or application.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// The URL to the profile's website or application. Only `https` or `http` URLs are allowed. No `@` signs are allowed.
    #[serde(rename = "website", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub website: Option<Option<String>>,
    /// The email address associated with the profile's trade name or brand.  If the domain contains non-ASCII characters, encode it as Punycode per [RFC 3492](https://www.rfc-editor.org/rfc/rfc3492).
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    /// The phone number associated with the profile's trade name or brand.
    #[serde(rename = "phone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub phone: Option<Option<String>>,
    /// The products or services offered by the profile's website or application.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// A list of countries where you expect that the majority of the profile's customers reside, in [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) format.
    #[serde(rename = "countriesOfActivity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub countries_of_activity: Option<Option<Vec<String>>>,
    /// The industry associated with the profile's trade name or brand. Please refer to the [business category list](common-data-types) for all possible options.
    #[serde(rename = "businessCategory", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub business_category: Option<Option<String>>,
    /// Updating a profile from `test` mode to `live` mode will trigger a verification process, where we review the profile before it can start accepting payments.
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::Mode>,
}

impl UpdateProfileRequest {
    pub fn new() -> UpdateProfileRequest {
        UpdateProfileRequest {
            name: None,
            website: None,
            email: None,
            phone: None,
            description: None,
            countries_of_activity: None,
            business_category: None,
            mode: None,
        }
    }
}

