/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSalesInvoiceRequest {
    /// Whether the entity was created in test mode or live mode. This field does not update the mode of the entity.  Most API credentials are specifically created for either live mode or test mode, in which case this parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
    #[serde(rename = "testmode", skip_serializing_if = "Option::is_none")]
    pub testmode: Option<bool>,
    /// The status for the invoice to end up in.  Dependent parameters: `paymentDetails` for `paid`, `emailDetails` for `issued` and `paid`.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::SalesInvoiceStatusUpdate>,
    /// A free-form memo you can set on the invoice, and will be shown on the invoice PDF.
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "paymentTerm", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_term: Option<Option<models::SalesInvoicePaymentTerm>>,
    /// Used when setting an invoice to status of `paid`, and will store a payment that fully pays the invoice with the provided details. Required for `paid` status.
    #[serde(rename = "paymentDetails", skip_serializing_if = "Option::is_none")]
    pub payment_details: Option<models::SalesInvoicePaymentDetails>,
    /// Used when setting an invoice to status of either `issued` or `paid`. Will be used to issue the invoice to the recipient with the provided `subject` and `body`. Required for `issued` status.
    #[serde(rename = "emailDetails", skip_serializing_if = "Option::is_none")]
    pub email_details: Option<models::SalesInvoiceEmailDetails>,
    /// An identifier tied to the recipient data. This should be a unique value based on data your system contains, so that both you and us know who we're referring to. It is a value you provide to us so that recipient management is not required to send a first invoice to a recipient.
    #[serde(rename = "recipientIdentifier", skip_serializing_if = "Option::is_none")]
    pub recipient_identifier: Option<String>,
    /// The recipient object should contain all the information relevant to create an invoice for an intended recipient. This data will be stored, updated, and re-used as appropriate, based on the `recipientIdentifier`.
    #[serde(rename = "recipient", skip_serializing_if = "Option::is_none")]
    pub recipient: Option<models::SalesInvoiceRecipient>,
    /// Provide the line items for the invoice. Each line contains details such as a description of the item ordered and its price.  All lines must have the same currency as the invoice.
    #[serde(rename = "lines", skip_serializing_if = "Option::is_none")]
    pub lines: Option<Vec<models::SalesInvoiceLineItem>>,
    /// The discount to be applied to the entire invoice, possibly on top of the line item discounts.
    #[serde(rename = "discount", skip_serializing_if = "Option::is_none")]
    pub discount: Option<models::SalesInvoiceDiscount>,
    /// This indicates whether the invoice is an e-invoice. The default value is `false` and can't be changed after the invoice has been issued.  When `emailDetails` is provided, an additional email is sent to the recipient.
    #[serde(rename = "isEInvoice", skip_serializing_if = "Option::is_none")]
    pub is_e_invoice: Option<bool>,
}

impl UpdateSalesInvoiceRequest {
    pub fn new() -> UpdateSalesInvoiceRequest {
        UpdateSalesInvoiceRequest {
            testmode: None,
            status: None,
            memo: None,
            payment_term: None,
            payment_details: None,
            email_details: None,
            recipient_identifier: None,
            recipient: None,
            lines: None,
            discount: None,
            is_e_invoice: None,
        }
    }
}

