/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VerificationOfPayeeRequest : The request body for performing a Verification of Payee (VoP) check. VoP allows you to verify the account holder name against the records held by the receiving bank before initiating a transfer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerificationOfPayeeRequest {
    /// The bank account details of the creditor (recipient) to verify.
    #[serde(rename = "creditorBankAccount")]
    pub creditor_bank_account: models::CreditorBankAccount,
    /// Whether to create the entity in test mode or live mode.  Most API credentials are specifically created for either live mode or test mode, in which case this parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
    #[serde(rename = "testmode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub testmode: Option<Option<bool>>,
}

impl VerificationOfPayeeRequest {
    /// The request body for performing a Verification of Payee (VoP) check. VoP allows you to verify the account holder name against the records held by the receiving bank before initiating a transfer.
    pub fn new(creditor_bank_account: models::CreditorBankAccount) -> VerificationOfPayeeRequest {
        VerificationOfPayeeRequest {
            creditor_bank_account,
            testmode: None,
        }
    }
}

