/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Voucher {
    /// Indicates the response contains a payment method issuer object. Will always contain the string `issuer` for this endpoint.
    #[serde(rename = "resource")]
    pub resource: String,
    /// The unique identifier of the payment method issuer.
    #[serde(rename = "id")]
    pub id: String,
    /// The full name of the payment method issuer.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "image")]
    pub image: Box<models::VoucherImage>,
    #[serde(rename = "status")]
    pub status: models::MethodIssuerStatus,
    #[serde(rename = "contractor")]
    pub contractor: Box<models::VoucherContractor>,
    #[serde(rename = "_links")]
    pub _links: Box<models::EntityBalanceLinks>,
}

impl Voucher {
    pub fn new(resource: String, id: String, name: String, image: models::VoucherImage, status: models::MethodIssuerStatus, contractor: models::VoucherContractor, _links: models::EntityBalanceLinks) -> Voucher {
        Voucher {
            resource,
            id,
            name,
            image: Box::new(image),
            status,
            contractor: Box::new(contractor),
            _links: Box::new(_links),
        }
    }
}

