/*
 * Mollie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Zomatree <me@zomatree.live>
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookStatus : The subscription's current status.
/// The subscription's current status.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebhookStatus {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "disabled")]
    Disabled,
    #[serde(rename = "deleted")]
    Deleted,

}

impl std::fmt::Display for WebhookStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Enabled => write!(f, "enabled"),
            Self::Blocked => write!(f, "blocked"),
            Self::Disabled => write!(f, "disabled"),
            Self::Deleted => write!(f, "deleted"),
        }
    }
}

impl Default for WebhookStatus {
    fn default() -> WebhookStatus {
        Self::Enabled
    }
}

